// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  CreateOrderItemRequest dco_decode_box_autoadd_create_order_item_request(
      dynamic raw);

  @protected
  CreateOrderRequest dco_decode_box_autoadd_create_order_request(dynamic raw);

  @protected
  CreatePortRequest dco_decode_box_autoadd_create_port_request(dynamic raw);

  @protected
  CreateShipRequest dco_decode_box_autoadd_create_ship_request(dynamic raw);

  @protected
  CreateShipVisitRequest dco_decode_box_autoadd_create_ship_visit_request(
      dynamic raw);

  @protected
  CreateStockMovementRequest
      dco_decode_box_autoadd_create_stock_movement_request(dynamic raw);

  @protected
  CreateStockRequest dco_decode_box_autoadd_create_stock_request(dynamic raw);

  @protected
  CreateSupplierRequest dco_decode_box_autoadd_create_supplier_request(
      dynamic raw);

  @protected
  CreateSupplyItemRequest dco_decode_box_autoadd_create_supply_item_request(
      dynamic raw);

  @protected
  DeliveryType dco_decode_box_autoadd_delivery_type(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  OrderStatus dco_decode_box_autoadd_order_status(dynamic raw);

  @protected
  OrderWithItems dco_decode_box_autoadd_order_with_items(dynamic raw);

  @protected
  Port dco_decode_box_autoadd_port(dynamic raw);

  @protected
  Ship dco_decode_box_autoadd_ship(dynamic raw);

  @protected
  ShipVisit dco_decode_box_autoadd_ship_visit(dynamic raw);

  @protected
  Stock dco_decode_box_autoadd_stock(dynamic raw);

  @protected
  StockWithMovements dco_decode_box_autoadd_stock_with_movements(dynamic raw);

  @protected
  Supplier dco_decode_box_autoadd_supplier(dynamic raw);

  @protected
  SupplyItem dco_decode_box_autoadd_supply_item(dynamic raw);

  @protected
  UpdateOrderItemRequest dco_decode_box_autoadd_update_order_item_request(
      dynamic raw);

  @protected
  UpdatePortRequest dco_decode_box_autoadd_update_port_request(dynamic raw);

  @protected
  UpdateShipRequest dco_decode_box_autoadd_update_ship_request(dynamic raw);

  @protected
  UpdateShipVisitRequest dco_decode_box_autoadd_update_ship_visit_request(
      dynamic raw);

  @protected
  UpdateStockRequest dco_decode_box_autoadd_update_stock_request(dynamic raw);

  @protected
  UpdateSupplierRequest dco_decode_box_autoadd_update_supplier_request(
      dynamic raw);

  @protected
  UpdateSupplyItemRequest dco_decode_box_autoadd_update_supply_item_request(
      dynamic raw);

  @protected
  VisitStatus dco_decode_box_autoadd_visit_status(dynamic raw);

  @protected
  CalendarData dco_decode_calendar_data(dynamic raw);

  @protected
  CalendarEvent dco_decode_calendar_event(dynamic raw);

  @protected
  CalendarEventType dco_decode_calendar_event_type(dynamic raw);

  @protected
  CreateOrderItemRequest dco_decode_create_order_item_request(dynamic raw);

  @protected
  CreateOrderRequest dco_decode_create_order_request(dynamic raw);

  @protected
  CreatePortRequest dco_decode_create_port_request(dynamic raw);

  @protected
  CreateShipRequest dco_decode_create_ship_request(dynamic raw);

  @protected
  CreateShipVisitRequest dco_decode_create_ship_visit_request(dynamic raw);

  @protected
  CreateStockMovementRequest dco_decode_create_stock_movement_request(
      dynamic raw);

  @protected
  CreateStockRequest dco_decode_create_stock_request(dynamic raw);

  @protected
  CreateSupplierRequest dco_decode_create_supplier_request(dynamic raw);

  @protected
  CreateSupplyItemRequest dco_decode_create_supply_item_request(dynamic raw);

  @protected
  DeliveryType dco_decode_delivery_type(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  ItemProfit dco_decode_item_profit(dynamic raw);

  @protected
  List<CalendarEvent> dco_decode_list_calendar_event(dynamic raw);

  @protected
  List<Order> dco_decode_list_order(dynamic raw);

  @protected
  List<OrderItem> dco_decode_list_order_item(dynamic raw);

  @protected
  List<Port> dco_decode_list_port(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<Ship> dco_decode_list_ship(dynamic raw);

  @protected
  List<ShipVisit> dco_decode_list_ship_visit(dynamic raw);

  @protected
  List<Stock> dco_decode_list_stock(dynamic raw);

  @protected
  List<StockMovement> dco_decode_list_stock_movement(dynamic raw);

  @protected
  List<Supplier> dco_decode_list_supplier(dynamic raw);

  @protected
  List<SupplyItem> dco_decode_list_supply_item(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  DeliveryType? dco_decode_opt_box_autoadd_delivery_type(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  OrderStatus? dco_decode_opt_box_autoadd_order_status(dynamic raw);

  @protected
  OrderWithItems? dco_decode_opt_box_autoadd_order_with_items(dynamic raw);

  @protected
  Port? dco_decode_opt_box_autoadd_port(dynamic raw);

  @protected
  Ship? dco_decode_opt_box_autoadd_ship(dynamic raw);

  @protected
  ShipVisit? dco_decode_opt_box_autoadd_ship_visit(dynamic raw);

  @protected
  Stock? dco_decode_opt_box_autoadd_stock(dynamic raw);

  @protected
  StockWithMovements? dco_decode_opt_box_autoadd_stock_with_movements(
      dynamic raw);

  @protected
  Supplier? dco_decode_opt_box_autoadd_supplier(dynamic raw);

  @protected
  SupplyItem? dco_decode_opt_box_autoadd_supply_item(dynamic raw);

  @protected
  VisitStatus? dco_decode_opt_box_autoadd_visit_status(dynamic raw);

  @protected
  Order dco_decode_order(dynamic raw);

  @protected
  OrderItem dco_decode_order_item(dynamic raw);

  @protected
  OrderStatus dco_decode_order_status(dynamic raw);

  @protected
  OrderTotals dco_decode_order_totals(dynamic raw);

  @protected
  OrderWithItems dco_decode_order_with_items(dynamic raw);

  @protected
  Port dco_decode_port(dynamic raw);

  @protected
  Ship dco_decode_ship(dynamic raw);

  @protected
  ShipVisit dco_decode_ship_visit(dynamic raw);

  @protected
  Stock dco_decode_stock(dynamic raw);

  @protected
  StockMovement dco_decode_stock_movement(dynamic raw);

  @protected
  StockMovementType dco_decode_stock_movement_type(dynamic raw);

  @protected
  StockSummary dco_decode_stock_summary(dynamic raw);

  @protected
  StockWithMovements dco_decode_stock_with_movements(dynamic raw);

  @protected
  Supplier dco_decode_supplier(dynamic raw);

  @protected
  SupplyItem dco_decode_supply_item(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UpdateOrderItemRequest dco_decode_update_order_item_request(dynamic raw);

  @protected
  UpdatePortRequest dco_decode_update_port_request(dynamic raw);

  @protected
  UpdateShipRequest dco_decode_update_ship_request(dynamic raw);

  @protected
  UpdateShipVisitRequest dco_decode_update_ship_visit_request(dynamic raw);

  @protected
  UpdateStockRequest dco_decode_update_stock_request(dynamic raw);

  @protected
  UpdateSupplierRequest dco_decode_update_supplier_request(dynamic raw);

  @protected
  UpdateSupplyItemRequest dco_decode_update_supply_item_request(dynamic raw);

  @protected
  VisitStatus dco_decode_visit_status(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  CreateOrderItemRequest sse_decode_box_autoadd_create_order_item_request(
      SseDeserializer deserializer);

  @protected
  CreateOrderRequest sse_decode_box_autoadd_create_order_request(
      SseDeserializer deserializer);

  @protected
  CreatePortRequest sse_decode_box_autoadd_create_port_request(
      SseDeserializer deserializer);

  @protected
  CreateShipRequest sse_decode_box_autoadd_create_ship_request(
      SseDeserializer deserializer);

  @protected
  CreateShipVisitRequest sse_decode_box_autoadd_create_ship_visit_request(
      SseDeserializer deserializer);

  @protected
  CreateStockMovementRequest
      sse_decode_box_autoadd_create_stock_movement_request(
          SseDeserializer deserializer);

  @protected
  CreateStockRequest sse_decode_box_autoadd_create_stock_request(
      SseDeserializer deserializer);

  @protected
  CreateSupplierRequest sse_decode_box_autoadd_create_supplier_request(
      SseDeserializer deserializer);

  @protected
  CreateSupplyItemRequest sse_decode_box_autoadd_create_supply_item_request(
      SseDeserializer deserializer);

  @protected
  DeliveryType sse_decode_box_autoadd_delivery_type(
      SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  OrderStatus sse_decode_box_autoadd_order_status(SseDeserializer deserializer);

  @protected
  OrderWithItems sse_decode_box_autoadd_order_with_items(
      SseDeserializer deserializer);

  @protected
  Port sse_decode_box_autoadd_port(SseDeserializer deserializer);

  @protected
  Ship sse_decode_box_autoadd_ship(SseDeserializer deserializer);

  @protected
  ShipVisit sse_decode_box_autoadd_ship_visit(SseDeserializer deserializer);

  @protected
  Stock sse_decode_box_autoadd_stock(SseDeserializer deserializer);

  @protected
  StockWithMovements sse_decode_box_autoadd_stock_with_movements(
      SseDeserializer deserializer);

  @protected
  Supplier sse_decode_box_autoadd_supplier(SseDeserializer deserializer);

  @protected
  SupplyItem sse_decode_box_autoadd_supply_item(SseDeserializer deserializer);

  @protected
  UpdateOrderItemRequest sse_decode_box_autoadd_update_order_item_request(
      SseDeserializer deserializer);

  @protected
  UpdatePortRequest sse_decode_box_autoadd_update_port_request(
      SseDeserializer deserializer);

  @protected
  UpdateShipRequest sse_decode_box_autoadd_update_ship_request(
      SseDeserializer deserializer);

  @protected
  UpdateShipVisitRequest sse_decode_box_autoadd_update_ship_visit_request(
      SseDeserializer deserializer);

  @protected
  UpdateStockRequest sse_decode_box_autoadd_update_stock_request(
      SseDeserializer deserializer);

  @protected
  UpdateSupplierRequest sse_decode_box_autoadd_update_supplier_request(
      SseDeserializer deserializer);

  @protected
  UpdateSupplyItemRequest sse_decode_box_autoadd_update_supply_item_request(
      SseDeserializer deserializer);

  @protected
  VisitStatus sse_decode_box_autoadd_visit_status(SseDeserializer deserializer);

  @protected
  CalendarData sse_decode_calendar_data(SseDeserializer deserializer);

  @protected
  CalendarEvent sse_decode_calendar_event(SseDeserializer deserializer);

  @protected
  CalendarEventType sse_decode_calendar_event_type(
      SseDeserializer deserializer);

  @protected
  CreateOrderItemRequest sse_decode_create_order_item_request(
      SseDeserializer deserializer);

  @protected
  CreateOrderRequest sse_decode_create_order_request(
      SseDeserializer deserializer);

  @protected
  CreatePortRequest sse_decode_create_port_request(
      SseDeserializer deserializer);

  @protected
  CreateShipRequest sse_decode_create_ship_request(
      SseDeserializer deserializer);

  @protected
  CreateShipVisitRequest sse_decode_create_ship_visit_request(
      SseDeserializer deserializer);

  @protected
  CreateStockMovementRequest sse_decode_create_stock_movement_request(
      SseDeserializer deserializer);

  @protected
  CreateStockRequest sse_decode_create_stock_request(
      SseDeserializer deserializer);

  @protected
  CreateSupplierRequest sse_decode_create_supplier_request(
      SseDeserializer deserializer);

  @protected
  CreateSupplyItemRequest sse_decode_create_supply_item_request(
      SseDeserializer deserializer);

  @protected
  DeliveryType sse_decode_delivery_type(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  ItemProfit sse_decode_item_profit(SseDeserializer deserializer);

  @protected
  List<CalendarEvent> sse_decode_list_calendar_event(
      SseDeserializer deserializer);

  @protected
  List<Order> sse_decode_list_order(SseDeserializer deserializer);

  @protected
  List<OrderItem> sse_decode_list_order_item(SseDeserializer deserializer);

  @protected
  List<Port> sse_decode_list_port(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<Ship> sse_decode_list_ship(SseDeserializer deserializer);

  @protected
  List<ShipVisit> sse_decode_list_ship_visit(SseDeserializer deserializer);

  @protected
  List<Stock> sse_decode_list_stock(SseDeserializer deserializer);

  @protected
  List<StockMovement> sse_decode_list_stock_movement(
      SseDeserializer deserializer);

  @protected
  List<Supplier> sse_decode_list_supplier(SseDeserializer deserializer);

  @protected
  List<SupplyItem> sse_decode_list_supply_item(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  DeliveryType? sse_decode_opt_box_autoadd_delivery_type(
      SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  OrderStatus? sse_decode_opt_box_autoadd_order_status(
      SseDeserializer deserializer);

  @protected
  OrderWithItems? sse_decode_opt_box_autoadd_order_with_items(
      SseDeserializer deserializer);

  @protected
  Port? sse_decode_opt_box_autoadd_port(SseDeserializer deserializer);

  @protected
  Ship? sse_decode_opt_box_autoadd_ship(SseDeserializer deserializer);

  @protected
  ShipVisit? sse_decode_opt_box_autoadd_ship_visit(
      SseDeserializer deserializer);

  @protected
  Stock? sse_decode_opt_box_autoadd_stock(SseDeserializer deserializer);

  @protected
  StockWithMovements? sse_decode_opt_box_autoadd_stock_with_movements(
      SseDeserializer deserializer);

  @protected
  Supplier? sse_decode_opt_box_autoadd_supplier(SseDeserializer deserializer);

  @protected
  SupplyItem? sse_decode_opt_box_autoadd_supply_item(
      SseDeserializer deserializer);

  @protected
  VisitStatus? sse_decode_opt_box_autoadd_visit_status(
      SseDeserializer deserializer);

  @protected
  Order sse_decode_order(SseDeserializer deserializer);

  @protected
  OrderItem sse_decode_order_item(SseDeserializer deserializer);

  @protected
  OrderStatus sse_decode_order_status(SseDeserializer deserializer);

  @protected
  OrderTotals sse_decode_order_totals(SseDeserializer deserializer);

  @protected
  OrderWithItems sse_decode_order_with_items(SseDeserializer deserializer);

  @protected
  Port sse_decode_port(SseDeserializer deserializer);

  @protected
  Ship sse_decode_ship(SseDeserializer deserializer);

  @protected
  ShipVisit sse_decode_ship_visit(SseDeserializer deserializer);

  @protected
  Stock sse_decode_stock(SseDeserializer deserializer);

  @protected
  StockMovement sse_decode_stock_movement(SseDeserializer deserializer);

  @protected
  StockMovementType sse_decode_stock_movement_type(
      SseDeserializer deserializer);

  @protected
  StockSummary sse_decode_stock_summary(SseDeserializer deserializer);

  @protected
  StockWithMovements sse_decode_stock_with_movements(
      SseDeserializer deserializer);

  @protected
  Supplier sse_decode_supplier(SseDeserializer deserializer);

  @protected
  SupplyItem sse_decode_supply_item(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UpdateOrderItemRequest sse_decode_update_order_item_request(
      SseDeserializer deserializer);

  @protected
  UpdatePortRequest sse_decode_update_port_request(
      SseDeserializer deserializer);

  @protected
  UpdateShipRequest sse_decode_update_ship_request(
      SseDeserializer deserializer);

  @protected
  UpdateShipVisitRequest sse_decode_update_ship_visit_request(
      SseDeserializer deserializer);

  @protected
  UpdateStockRequest sse_decode_update_stock_request(
      SseDeserializer deserializer);

  @protected
  UpdateSupplierRequest sse_decode_update_supplier_request(
      SseDeserializer deserializer);

  @protected
  UpdateSupplyItemRequest sse_decode_update_supply_item_request(
      SseDeserializer deserializer);

  @protected
  VisitStatus sse_decode_visit_status(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_create_order_item_request(
      CreateOrderItemRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_create_order_request(
      CreateOrderRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_create_port_request(
      CreatePortRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_create_ship_request(
      CreateShipRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_create_ship_visit_request(
      CreateShipVisitRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_create_stock_movement_request(
      CreateStockMovementRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_create_stock_request(
      CreateStockRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_create_supplier_request(
      CreateSupplierRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_create_supply_item_request(
      CreateSupplyItemRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_delivery_type(
      DeliveryType self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_order_status(
      OrderStatus self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_order_with_items(
      OrderWithItems self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_port(Port self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ship(Ship self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ship_visit(
      ShipVisit self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_stock(Stock self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_stock_with_movements(
      StockWithMovements self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_supplier(Supplier self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_supply_item(
      SupplyItem self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_update_order_item_request(
      UpdateOrderItemRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_update_port_request(
      UpdatePortRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_update_ship_request(
      UpdateShipRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_update_ship_visit_request(
      UpdateShipVisitRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_update_stock_request(
      UpdateStockRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_update_supplier_request(
      UpdateSupplierRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_update_supply_item_request(
      UpdateSupplyItemRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_visit_status(
      VisitStatus self, SseSerializer serializer);

  @protected
  void sse_encode_calendar_data(CalendarData self, SseSerializer serializer);

  @protected
  void sse_encode_calendar_event(CalendarEvent self, SseSerializer serializer);

  @protected
  void sse_encode_calendar_event_type(
      CalendarEventType self, SseSerializer serializer);

  @protected
  void sse_encode_create_order_item_request(
      CreateOrderItemRequest self, SseSerializer serializer);

  @protected
  void sse_encode_create_order_request(
      CreateOrderRequest self, SseSerializer serializer);

  @protected
  void sse_encode_create_port_request(
      CreatePortRequest self, SseSerializer serializer);

  @protected
  void sse_encode_create_ship_request(
      CreateShipRequest self, SseSerializer serializer);

  @protected
  void sse_encode_create_ship_visit_request(
      CreateShipVisitRequest self, SseSerializer serializer);

  @protected
  void sse_encode_create_stock_movement_request(
      CreateStockMovementRequest self, SseSerializer serializer);

  @protected
  void sse_encode_create_stock_request(
      CreateStockRequest self, SseSerializer serializer);

  @protected
  void sse_encode_create_supplier_request(
      CreateSupplierRequest self, SseSerializer serializer);

  @protected
  void sse_encode_create_supply_item_request(
      CreateSupplyItemRequest self, SseSerializer serializer);

  @protected
  void sse_encode_delivery_type(DeliveryType self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_item_profit(ItemProfit self, SseSerializer serializer);

  @protected
  void sse_encode_list_calendar_event(
      List<CalendarEvent> self, SseSerializer serializer);

  @protected
  void sse_encode_list_order(List<Order> self, SseSerializer serializer);

  @protected
  void sse_encode_list_order_item(
      List<OrderItem> self, SseSerializer serializer);

  @protected
  void sse_encode_list_port(List<Port> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_ship(List<Ship> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ship_visit(
      List<ShipVisit> self, SseSerializer serializer);

  @protected
  void sse_encode_list_stock(List<Stock> self, SseSerializer serializer);

  @protected
  void sse_encode_list_stock_movement(
      List<StockMovement> self, SseSerializer serializer);

  @protected
  void sse_encode_list_supplier(List<Supplier> self, SseSerializer serializer);

  @protected
  void sse_encode_list_supply_item(
      List<SupplyItem> self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_delivery_type(
      DeliveryType? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_order_status(
      OrderStatus? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_order_with_items(
      OrderWithItems? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_port(Port? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_ship(Ship? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_ship_visit(
      ShipVisit? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_stock(Stock? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_stock_with_movements(
      StockWithMovements? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_supplier(
      Supplier? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_supply_item(
      SupplyItem? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_visit_status(
      VisitStatus? self, SseSerializer serializer);

  @protected
  void sse_encode_order(Order self, SseSerializer serializer);

  @protected
  void sse_encode_order_item(OrderItem self, SseSerializer serializer);

  @protected
  void sse_encode_order_status(OrderStatus self, SseSerializer serializer);

  @protected
  void sse_encode_order_totals(OrderTotals self, SseSerializer serializer);

  @protected
  void sse_encode_order_with_items(
      OrderWithItems self, SseSerializer serializer);

  @protected
  void sse_encode_port(Port self, SseSerializer serializer);

  @protected
  void sse_encode_ship(Ship self, SseSerializer serializer);

  @protected
  void sse_encode_ship_visit(ShipVisit self, SseSerializer serializer);

  @protected
  void sse_encode_stock(Stock self, SseSerializer serializer);

  @protected
  void sse_encode_stock_movement(StockMovement self, SseSerializer serializer);

  @protected
  void sse_encode_stock_movement_type(
      StockMovementType self, SseSerializer serializer);

  @protected
  void sse_encode_stock_summary(StockSummary self, SseSerializer serializer);

  @protected
  void sse_encode_stock_with_movements(
      StockWithMovements self, SseSerializer serializer);

  @protected
  void sse_encode_supplier(Supplier self, SseSerializer serializer);

  @protected
  void sse_encode_supply_item(SupplyItem self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_update_order_item_request(
      UpdateOrderItemRequest self, SseSerializer serializer);

  @protected
  void sse_encode_update_port_request(
      UpdatePortRequest self, SseSerializer serializer);

  @protected
  void sse_encode_update_ship_request(
      UpdateShipRequest self, SseSerializer serializer);

  @protected
  void sse_encode_update_ship_visit_request(
      UpdateShipVisitRequest self, SseSerializer serializer);

  @protected
  void sse_encode_update_stock_request(
      UpdateStockRequest self, SseSerializer serializer);

  @protected
  void sse_encode_update_supplier_request(
      UpdateSupplierRequest self, SseSerializer serializer);

  @protected
  void sse_encode_update_supply_item_request(
      UpdateSupplyItemRequest self, SseSerializer serializer);

  @protected
  void sse_encode_visit_status(VisitStatus self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;
}
