// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field


// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';




                abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
                  RustLibApiImplPlatform({
                    required super.handler,
                    required super.wire,
                    required super.generalizedFrbRustBinding,
                    required super.portManager,
                  });

                  

                  @protected String dco_decode_String(dynamic raw);

@protected bool dco_decode_bool(dynamic raw);

@protected CreateOrderItemRequest dco_decode_box_autoadd_create_order_item_request(dynamic raw);

@protected CreateOrderRequest dco_decode_box_autoadd_create_order_request(dynamic raw);

@protected CreateShipRequest dco_decode_box_autoadd_create_ship_request(dynamic raw);

@protected CreateSupplierRequest dco_decode_box_autoadd_create_supplier_request(dynamic raw);

@protected double dco_decode_box_autoadd_f_64(dynamic raw);

@protected OrderStatus dco_decode_box_autoadd_order_status(dynamic raw);

@protected OrderWithItems dco_decode_box_autoadd_order_with_items(dynamic raw);

@protected Ship dco_decode_box_autoadd_ship(dynamic raw);

@protected UpdateOrderItemRequest dco_decode_box_autoadd_update_order_item_request(dynamic raw);

@protected UpdateShipRequest dco_decode_box_autoadd_update_ship_request(dynamic raw);

@protected CreateOrderItemRequest dco_decode_create_order_item_request(dynamic raw);

@protected CreateOrderRequest dco_decode_create_order_request(dynamic raw);

@protected CreateShipRequest dco_decode_create_ship_request(dynamic raw);

@protected CreateSupplierRequest dco_decode_create_supplier_request(dynamic raw);

@protected double dco_decode_f_64(dynamic raw);

@protected int dco_decode_i_32(dynamic raw);

@protected ItemProfit dco_decode_item_profit(dynamic raw);

@protected List<Order> dco_decode_list_order(dynamic raw);

@protected List<OrderItem> dco_decode_list_order_item(dynamic raw);

@protected Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

@protected List<Ship> dco_decode_list_ship(dynamic raw);

@protected List<Supplier> dco_decode_list_supplier(dynamic raw);

@protected String? dco_decode_opt_String(dynamic raw);

@protected double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

@protected OrderStatus? dco_decode_opt_box_autoadd_order_status(dynamic raw);

@protected OrderWithItems? dco_decode_opt_box_autoadd_order_with_items(dynamic raw);

@protected Ship? dco_decode_opt_box_autoadd_ship(dynamic raw);

@protected Order dco_decode_order(dynamic raw);

@protected OrderItem dco_decode_order_item(dynamic raw);

@protected OrderStatus dco_decode_order_status(dynamic raw);

@protected OrderTotals dco_decode_order_totals(dynamic raw);

@protected OrderWithItems dco_decode_order_with_items(dynamic raw);

@protected Ship dco_decode_ship(dynamic raw);

@protected Supplier dco_decode_supplier(dynamic raw);

@protected int dco_decode_u_8(dynamic raw);

@protected void dco_decode_unit(dynamic raw);

@protected UpdateOrderItemRequest dco_decode_update_order_item_request(dynamic raw);

@protected UpdateShipRequest dco_decode_update_ship_request(dynamic raw);

@protected String sse_decode_String(SseDeserializer deserializer);

@protected bool sse_decode_bool(SseDeserializer deserializer);

@protected CreateOrderItemRequest sse_decode_box_autoadd_create_order_item_request(SseDeserializer deserializer);

@protected CreateOrderRequest sse_decode_box_autoadd_create_order_request(SseDeserializer deserializer);

@protected CreateShipRequest sse_decode_box_autoadd_create_ship_request(SseDeserializer deserializer);

@protected CreateSupplierRequest sse_decode_box_autoadd_create_supplier_request(SseDeserializer deserializer);

@protected double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

@protected OrderStatus sse_decode_box_autoadd_order_status(SseDeserializer deserializer);

@protected OrderWithItems sse_decode_box_autoadd_order_with_items(SseDeserializer deserializer);

@protected Ship sse_decode_box_autoadd_ship(SseDeserializer deserializer);

@protected UpdateOrderItemRequest sse_decode_box_autoadd_update_order_item_request(SseDeserializer deserializer);

@protected UpdateShipRequest sse_decode_box_autoadd_update_ship_request(SseDeserializer deserializer);

@protected CreateOrderItemRequest sse_decode_create_order_item_request(SseDeserializer deserializer);

@protected CreateOrderRequest sse_decode_create_order_request(SseDeserializer deserializer);

@protected CreateShipRequest sse_decode_create_ship_request(SseDeserializer deserializer);

@protected CreateSupplierRequest sse_decode_create_supplier_request(SseDeserializer deserializer);

@protected double sse_decode_f_64(SseDeserializer deserializer);

@protected int sse_decode_i_32(SseDeserializer deserializer);

@protected ItemProfit sse_decode_item_profit(SseDeserializer deserializer);

@protected List<Order> sse_decode_list_order(SseDeserializer deserializer);

@protected List<OrderItem> sse_decode_list_order_item(SseDeserializer deserializer);

@protected Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

@protected List<Ship> sse_decode_list_ship(SseDeserializer deserializer);

@protected List<Supplier> sse_decode_list_supplier(SseDeserializer deserializer);

@protected String? sse_decode_opt_String(SseDeserializer deserializer);

@protected double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

@protected OrderStatus? sse_decode_opt_box_autoadd_order_status(SseDeserializer deserializer);

@protected OrderWithItems? sse_decode_opt_box_autoadd_order_with_items(SseDeserializer deserializer);

@protected Ship? sse_decode_opt_box_autoadd_ship(SseDeserializer deserializer);

@protected Order sse_decode_order(SseDeserializer deserializer);

@protected OrderItem sse_decode_order_item(SseDeserializer deserializer);

@protected OrderStatus sse_decode_order_status(SseDeserializer deserializer);

@protected OrderTotals sse_decode_order_totals(SseDeserializer deserializer);

@protected OrderWithItems sse_decode_order_with_items(SseDeserializer deserializer);

@protected Ship sse_decode_ship(SseDeserializer deserializer);

@protected Supplier sse_decode_supplier(SseDeserializer deserializer);

@protected int sse_decode_u_8(SseDeserializer deserializer);

@protected void sse_decode_unit(SseDeserializer deserializer);

@protected UpdateOrderItemRequest sse_decode_update_order_item_request(SseDeserializer deserializer);

@protected UpdateShipRequest sse_decode_update_ship_request(SseDeserializer deserializer);

@protected void sse_encode_String(String self, SseSerializer serializer);

@protected void sse_encode_bool(bool self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_create_order_item_request(CreateOrderItemRequest self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_create_order_request(CreateOrderRequest self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_create_ship_request(CreateShipRequest self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_create_supplier_request(CreateSupplierRequest self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_order_status(OrderStatus self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_order_with_items(OrderWithItems self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_ship(Ship self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_update_order_item_request(UpdateOrderItemRequest self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_update_ship_request(UpdateShipRequest self, SseSerializer serializer);

@protected void sse_encode_create_order_item_request(CreateOrderItemRequest self, SseSerializer serializer);

@protected void sse_encode_create_order_request(CreateOrderRequest self, SseSerializer serializer);

@protected void sse_encode_create_ship_request(CreateShipRequest self, SseSerializer serializer);

@protected void sse_encode_create_supplier_request(CreateSupplierRequest self, SseSerializer serializer);

@protected void sse_encode_f_64(double self, SseSerializer serializer);

@protected void sse_encode_i_32(int self, SseSerializer serializer);

@protected void sse_encode_item_profit(ItemProfit self, SseSerializer serializer);

@protected void sse_encode_list_order(List<Order> self, SseSerializer serializer);

@protected void sse_encode_list_order_item(List<OrderItem> self, SseSerializer serializer);

@protected void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer);

@protected void sse_encode_list_ship(List<Ship> self, SseSerializer serializer);

@protected void sse_encode_list_supplier(List<Supplier> self, SseSerializer serializer);

@protected void sse_encode_opt_String(String? self, SseSerializer serializer);

@protected void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

@protected void sse_encode_opt_box_autoadd_order_status(OrderStatus? self, SseSerializer serializer);

@protected void sse_encode_opt_box_autoadd_order_with_items(OrderWithItems? self, SseSerializer serializer);

@protected void sse_encode_opt_box_autoadd_ship(Ship? self, SseSerializer serializer);

@protected void sse_encode_order(Order self, SseSerializer serializer);

@protected void sse_encode_order_item(OrderItem self, SseSerializer serializer);

@protected void sse_encode_order_status(OrderStatus self, SseSerializer serializer);

@protected void sse_encode_order_totals(OrderTotals self, SseSerializer serializer);

@protected void sse_encode_order_with_items(OrderWithItems self, SseSerializer serializer);

@protected void sse_encode_ship(Ship self, SseSerializer serializer);

@protected void sse_encode_supplier(Supplier self, SseSerializer serializer);

@protected void sse_encode_u_8(int self, SseSerializer serializer);

@protected void sse_encode_unit(void self, SseSerializer serializer);

@protected void sse_encode_update_order_item_request(UpdateOrderItemRequest self, SseSerializer serializer);

@protected void sse_encode_update_ship_request(UpdateShipRequest self, SseSerializer serializer);
                }
                


// Section: wire_class

class RustLibWire implements BaseWire {
            RustLibWire.fromExternalLibrary(ExternalLibrary lib);

            
        }
        @JS('wasm_bindgen') external RustLibWasmModule get wasmModule;

        @JS() @anonymous extension type RustLibWasmModule._(JSObject _) implements JSObject {
            
        }
        