// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1238438420;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'ssms_core',
    ioDirectory: '../backend/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<OrderItem> crateApiAddOrderItem(
      {required CreateOrderItemRequest item});

  Future<ItemProfit> crateApiCalculateItemProfit(
      {required double buyingPrice,
      required double sellingPrice,
      required double quantity});

  Future<OrderTotals> crateApiCalculateOrderTotals({required int orderId});

  Future<Order> crateApiCreateOrder({required CreateOrderRequest order});

  Future<Ship> crateApiCreateShip({required CreateShipRequest ship});

  Future<Supplier> crateApiCreateSupplier(
      {required CreateSupplierRequest supplier});

  Future<bool> crateApiDeleteOrderItem({required int id});

  Future<bool> crateApiDeleteShip({required int id});

  Future<List<Order>> crateApiGetAllOrders({OrderStatus? statusFilter});

  Future<List<Ship>> crateApiGetAllShips();

  Future<List<Supplier>> crateApiGetAllSuppliers();

  Future<OrderWithItems?> crateApiGetOrderWithItems({required int id});

  Future<Ship?> crateApiGetShipById({required int id});

  Future<String> crateApiGetVersion();

  Future<String> crateApiGreet({required String name});

  Future<void> crateApiInitDatabase({required String databaseUrl});

  Future<bool> crateApiIsDatabaseConnected();

  Future<OrderItem> crateApiUpdateOrderItem(
      {required int id, required UpdateOrderItemRequest item});

  Future<Order> crateApiUpdateOrderStatus(
      {required int id, required OrderStatus newStatus});

  Future<Ship> crateApiUpdateShip(
      {required int id, required UpdateShipRequest ship});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<OrderItem> crateApiAddOrderItem(
      {required CreateOrderItemRequest item}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_create_order_item_request(item, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_order_item,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiAddOrderItemConstMeta,
      argValues: [item],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAddOrderItemConstMeta => const TaskConstMeta(
        debugName: "add_order_item",
        argNames: ["item"],
      );

  @override
  Future<ItemProfit> crateApiCalculateItemProfit(
      {required double buyingPrice,
      required double sellingPrice,
      required double quantity}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_f_64(buyingPrice, serializer);
        sse_encode_f_64(sellingPrice, serializer);
        sse_encode_f_64(quantity, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_item_profit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCalculateItemProfitConstMeta,
      argValues: [buyingPrice, sellingPrice, quantity],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCalculateItemProfitConstMeta =>
      const TaskConstMeta(
        debugName: "calculate_item_profit",
        argNames: ["buyingPrice", "sellingPrice", "quantity"],
      );

  @override
  Future<OrderTotals> crateApiCalculateOrderTotals({required int orderId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_32(orderId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_order_totals,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiCalculateOrderTotalsConstMeta,
      argValues: [orderId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCalculateOrderTotalsConstMeta =>
      const TaskConstMeta(
        debugName: "calculate_order_totals",
        argNames: ["orderId"],
      );

  @override
  Future<Order> crateApiCreateOrder({required CreateOrderRequest order}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_create_order_request(order, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_order,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiCreateOrderConstMeta,
      argValues: [order],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCreateOrderConstMeta => const TaskConstMeta(
        debugName: "create_order",
        argNames: ["order"],
      );

  @override
  Future<Ship> crateApiCreateShip({required CreateShipRequest ship}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_create_ship_request(ship, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_ship,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiCreateShipConstMeta,
      argValues: [ship],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCreateShipConstMeta => const TaskConstMeta(
        debugName: "create_ship",
        argNames: ["ship"],
      );

  @override
  Future<Supplier> crateApiCreateSupplier(
      {required CreateSupplierRequest supplier}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_create_supplier_request(supplier, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_supplier,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiCreateSupplierConstMeta,
      argValues: [supplier],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCreateSupplierConstMeta => const TaskConstMeta(
        debugName: "create_supplier",
        argNames: ["supplier"],
      );

  @override
  Future<bool> crateApiDeleteOrderItem({required int id}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_32(id, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiDeleteOrderItemConstMeta,
      argValues: [id],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDeleteOrderItemConstMeta => const TaskConstMeta(
        debugName: "delete_order_item",
        argNames: ["id"],
      );

  @override
  Future<bool> crateApiDeleteShip({required int id}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_32(id, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiDeleteShipConstMeta,
      argValues: [id],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDeleteShipConstMeta => const TaskConstMeta(
        debugName: "delete_ship",
        argNames: ["id"],
      );

  @override
  Future<List<Order>> crateApiGetAllOrders({OrderStatus? statusFilter}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_opt_box_autoadd_order_status(statusFilter, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_order,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGetAllOrdersConstMeta,
      argValues: [statusFilter],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetAllOrdersConstMeta => const TaskConstMeta(
        debugName: "get_all_orders",
        argNames: ["statusFilter"],
      );

  @override
  Future<List<Ship>> crateApiGetAllShips() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_ship,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGetAllShipsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetAllShipsConstMeta => const TaskConstMeta(
        debugName: "get_all_ships",
        argNames: [],
      );

  @override
  Future<List<Supplier>> crateApiGetAllSuppliers() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_supplier,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGetAllSuppliersConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetAllSuppliersConstMeta => const TaskConstMeta(
        debugName: "get_all_suppliers",
        argNames: [],
      );

  @override
  Future<OrderWithItems?> crateApiGetOrderWithItems({required int id}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_32(id, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_box_autoadd_order_with_items,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGetOrderWithItemsConstMeta,
      argValues: [id],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetOrderWithItemsConstMeta => const TaskConstMeta(
        debugName: "get_order_with_items",
        argNames: ["id"],
      );

  @override
  Future<Ship?> crateApiGetShipById({required int id}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_32(id, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_box_autoadd_ship,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGetShipByIdConstMeta,
      argValues: [id],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetShipByIdConstMeta => const TaskConstMeta(
        debugName: "get_ship_by_id",
        argNames: ["id"],
      );

  @override
  Future<String> crateApiGetVersion() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGetVersionConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetVersionConstMeta => const TaskConstMeta(
        debugName: "get_version",
        argNames: [],
      );

  @override
  Future<String> crateApiGreet({required String name}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGreetConstMeta,
      argValues: [name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGreetConstMeta => const TaskConstMeta(
        debugName: "greet",
        argNames: ["name"],
      );

  @override
  Future<void> crateApiInitDatabase({required String databaseUrl}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(databaseUrl, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiInitDatabaseConstMeta,
      argValues: [databaseUrl],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInitDatabaseConstMeta => const TaskConstMeta(
        debugName: "init_database",
        argNames: ["databaseUrl"],
      );

  @override
  Future<bool> crateApiIsDatabaseConnected() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiIsDatabaseConnectedConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiIsDatabaseConnectedConstMeta =>
      const TaskConstMeta(
        debugName: "is_database_connected",
        argNames: [],
      );

  @override
  Future<OrderItem> crateApiUpdateOrderItem(
      {required int id, required UpdateOrderItemRequest item}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_32(id, serializer);
        sse_encode_box_autoadd_update_order_item_request(item, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 18, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_order_item,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiUpdateOrderItemConstMeta,
      argValues: [id, item],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiUpdateOrderItemConstMeta => const TaskConstMeta(
        debugName: "update_order_item",
        argNames: ["id", "item"],
      );

  @override
  Future<Order> crateApiUpdateOrderStatus(
      {required int id, required OrderStatus newStatus}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_32(id, serializer);
        sse_encode_order_status(newStatus, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 19, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_order,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiUpdateOrderStatusConstMeta,
      argValues: [id, newStatus],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiUpdateOrderStatusConstMeta => const TaskConstMeta(
        debugName: "update_order_status",
        argNames: ["id", "newStatus"],
      );

  @override
  Future<Ship> crateApiUpdateShip(
      {required int id, required UpdateShipRequest ship}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_32(id, serializer);
        sse_encode_box_autoadd_update_ship_request(ship, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 20, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_ship,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiUpdateShipConstMeta,
      argValues: [id, ship],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiUpdateShipConstMeta => const TaskConstMeta(
        debugName: "update_ship",
        argNames: ["id", "ship"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  CreateOrderItemRequest dco_decode_box_autoadd_create_order_item_request(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_create_order_item_request(raw);
  }

  @protected
  CreateOrderRequest dco_decode_box_autoadd_create_order_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_create_order_request(raw);
  }

  @protected
  CreateShipRequest dco_decode_box_autoadd_create_ship_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_create_ship_request(raw);
  }

  @protected
  CreateSupplierRequest dco_decode_box_autoadd_create_supplier_request(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_create_supplier_request(raw);
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  OrderStatus dco_decode_box_autoadd_order_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_order_status(raw);
  }

  @protected
  OrderWithItems dco_decode_box_autoadd_order_with_items(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_order_with_items(raw);
  }

  @protected
  Ship dco_decode_box_autoadd_ship(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_ship(raw);
  }

  @protected
  UpdateOrderItemRequest dco_decode_box_autoadd_update_order_item_request(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_update_order_item_request(raw);
  }

  @protected
  UpdateShipRequest dco_decode_box_autoadd_update_ship_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_update_ship_request(raw);
  }

  @protected
  CreateOrderItemRequest dco_decode_create_order_item_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return CreateOrderItemRequest(
      orderId: dco_decode_i_32(arr[0]),
      productName: dco_decode_String(arr[1]),
      impaCode: dco_decode_opt_String(arr[2]),
      description: dco_decode_opt_String(arr[3]),
      quantity: dco_decode_f_64(arr[4]),
      unit: dco_decode_String(arr[5]),
      buyingPrice: dco_decode_f_64(arr[6]),
      sellingPrice: dco_decode_f_64(arr[7]),
      currency: dco_decode_String(arr[8]),
      notes: dco_decode_opt_String(arr[9]),
    );
  }

  @protected
  CreateOrderRequest dco_decode_create_order_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return CreateOrderRequest(
      shipId: dco_decode_i_32(arr[0]),
      deliveryPort: dco_decode_opt_String(arr[1]),
      deliveryDate: dco_decode_opt_String(arr[2]),
      notes: dco_decode_opt_String(arr[3]),
      currency: dco_decode_String(arr[4]),
    );
  }

  @protected
  CreateShipRequest dco_decode_create_ship_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return CreateShipRequest(
      name: dco_decode_String(arr[0]),
      imoNumber: dco_decode_String(arr[1]),
      flag: dco_decode_String(arr[2]),
      shipType: dco_decode_opt_String(arr[3]),
      grossTonnage: dco_decode_opt_box_autoadd_f_64(arr[4]),
      owner: dco_decode_opt_String(arr[5]),
    );
  }

  @protected
  CreateSupplierRequest dco_decode_create_supplier_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return CreateSupplierRequest(
      name: dco_decode_String(arr[0]),
      contactPerson: dco_decode_opt_String(arr[1]),
      email: dco_decode_opt_String(arr[2]),
      phone: dco_decode_opt_String(arr[3]),
      address: dco_decode_opt_String(arr[4]),
      country: dco_decode_opt_String(arr[5]),
      category: dco_decode_String(arr[6]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  ItemProfit dco_decode_item_profit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ItemProfit(
      totalCost: dco_decode_f_64(arr[0]),
      totalRevenue: dco_decode_f_64(arr[1]),
      grossProfit: dco_decode_f_64(arr[2]),
      marginPercent: dco_decode_opt_box_autoadd_f_64(arr[3]),
    );
  }

  @protected
  List<Order> dco_decode_list_order(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_order).toList();
  }

  @protected
  List<OrderItem> dco_decode_list_order_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_order_item).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<Ship> dco_decode_list_ship(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_ship).toList();
  }

  @protected
  List<Supplier> dco_decode_list_supplier(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_supplier).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  OrderStatus? dco_decode_opt_box_autoadd_order_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_order_status(raw);
  }

  @protected
  OrderWithItems? dco_decode_opt_box_autoadd_order_with_items(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_order_with_items(raw);
  }

  @protected
  Ship? dco_decode_opt_box_autoadd_ship(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_ship(raw);
  }

  @protected
  Order dco_decode_order(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return Order(
      id: dco_decode_i_32(arr[0]),
      orderNumber: dco_decode_String(arr[1]),
      shipId: dco_decode_i_32(arr[2]),
      shipName: dco_decode_opt_String(arr[3]),
      status: dco_decode_order_status(arr[4]),
      deliveryPort: dco_decode_opt_String(arr[5]),
      deliveryDate: dco_decode_opt_String(arr[6]),
      notes: dco_decode_opt_String(arr[7]),
      currency: dco_decode_String(arr[8]),
      createdAt: dco_decode_String(arr[9]),
      updatedAt: dco_decode_String(arr[10]),
    );
  }

  @protected
  OrderItem dco_decode_order_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return OrderItem(
      id: dco_decode_i_32(arr[0]),
      orderId: dco_decode_i_32(arr[1]),
      productName: dco_decode_String(arr[2]),
      impaCode: dco_decode_opt_String(arr[3]),
      description: dco_decode_opt_String(arr[4]),
      quantity: dco_decode_f_64(arr[5]),
      unit: dco_decode_String(arr[6]),
      buyingPrice: dco_decode_f_64(arr[7]),
      sellingPrice: dco_decode_f_64(arr[8]),
      currency: dco_decode_String(arr[9]),
      notes: dco_decode_opt_String(arr[10]),
    );
  }

  @protected
  OrderStatus dco_decode_order_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return OrderStatus.values[raw as int];
  }

  @protected
  OrderTotals dco_decode_order_totals(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return OrderTotals(
      itemCount: dco_decode_i_32(arr[0]),
      totalCost: dco_decode_f_64(arr[1]),
      totalRevenue: dco_decode_f_64(arr[2]),
      grossProfit: dco_decode_f_64(arr[3]),
      marginPercent: dco_decode_opt_box_autoadd_f_64(arr[4]),
      currency: dco_decode_String(arr[5]),
    );
  }

  @protected
  OrderWithItems dco_decode_order_with_items(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return OrderWithItems(
      order: dco_decode_order(arr[0]),
      items: dco_decode_list_order_item(arr[1]),
      totals: dco_decode_order_totals(arr[2]),
    );
  }

  @protected
  Ship dco_decode_ship(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return Ship(
      id: dco_decode_i_32(arr[0]),
      name: dco_decode_String(arr[1]),
      imoNumber: dco_decode_String(arr[2]),
      flag: dco_decode_String(arr[3]),
      shipType: dco_decode_opt_String(arr[4]),
      grossTonnage: dco_decode_opt_box_autoadd_f_64(arr[5]),
      owner: dco_decode_opt_String(arr[6]),
      createdAt: dco_decode_String(arr[7]),
      updatedAt: dco_decode_String(arr[8]),
    );
  }

  @protected
  Supplier dco_decode_supplier(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return Supplier(
      id: dco_decode_i_32(arr[0]),
      name: dco_decode_String(arr[1]),
      contactPerson: dco_decode_opt_String(arr[2]),
      email: dco_decode_opt_String(arr[3]),
      phone: dco_decode_opt_String(arr[4]),
      address: dco_decode_opt_String(arr[5]),
      country: dco_decode_opt_String(arr[6]),
      category: dco_decode_String(arr[7]),
      isActive: dco_decode_bool(arr[8]),
      createdAt: dco_decode_String(arr[9]),
      updatedAt: dco_decode_String(arr[10]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  UpdateOrderItemRequest dco_decode_update_order_item_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return UpdateOrderItemRequest(
      productName: dco_decode_opt_String(arr[0]),
      impaCode: dco_decode_opt_String(arr[1]),
      description: dco_decode_opt_String(arr[2]),
      quantity: dco_decode_opt_box_autoadd_f_64(arr[3]),
      unit: dco_decode_opt_String(arr[4]),
      buyingPrice: dco_decode_opt_box_autoadd_f_64(arr[5]),
      sellingPrice: dco_decode_opt_box_autoadd_f_64(arr[6]),
      notes: dco_decode_opt_String(arr[7]),
    );
  }

  @protected
  UpdateShipRequest dco_decode_update_ship_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return UpdateShipRequest(
      name: dco_decode_opt_String(arr[0]),
      imoNumber: dco_decode_opt_String(arr[1]),
      flag: dco_decode_opt_String(arr[2]),
      shipType: dco_decode_opt_String(arr[3]),
      grossTonnage: dco_decode_opt_box_autoadd_f_64(arr[4]),
      owner: dco_decode_opt_String(arr[5]),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  CreateOrderItemRequest sse_decode_box_autoadd_create_order_item_request(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_create_order_item_request(deserializer));
  }

  @protected
  CreateOrderRequest sse_decode_box_autoadd_create_order_request(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_create_order_request(deserializer));
  }

  @protected
  CreateShipRequest sse_decode_box_autoadd_create_ship_request(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_create_ship_request(deserializer));
  }

  @protected
  CreateSupplierRequest sse_decode_box_autoadd_create_supplier_request(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_create_supplier_request(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  OrderStatus sse_decode_box_autoadd_order_status(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_order_status(deserializer));
  }

  @protected
  OrderWithItems sse_decode_box_autoadd_order_with_items(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_order_with_items(deserializer));
  }

  @protected
  Ship sse_decode_box_autoadd_ship(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_ship(deserializer));
  }

  @protected
  UpdateOrderItemRequest sse_decode_box_autoadd_update_order_item_request(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_update_order_item_request(deserializer));
  }

  @protected
  UpdateShipRequest sse_decode_box_autoadd_update_ship_request(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_update_ship_request(deserializer));
  }

  @protected
  CreateOrderItemRequest sse_decode_create_order_item_request(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_orderId = sse_decode_i_32(deserializer);
    var var_productName = sse_decode_String(deserializer);
    var var_impaCode = sse_decode_opt_String(deserializer);
    var var_description = sse_decode_opt_String(deserializer);
    var var_quantity = sse_decode_f_64(deserializer);
    var var_unit = sse_decode_String(deserializer);
    var var_buyingPrice = sse_decode_f_64(deserializer);
    var var_sellingPrice = sse_decode_f_64(deserializer);
    var var_currency = sse_decode_String(deserializer);
    var var_notes = sse_decode_opt_String(deserializer);
    return CreateOrderItemRequest(
        orderId: var_orderId,
        productName: var_productName,
        impaCode: var_impaCode,
        description: var_description,
        quantity: var_quantity,
        unit: var_unit,
        buyingPrice: var_buyingPrice,
        sellingPrice: var_sellingPrice,
        currency: var_currency,
        notes: var_notes);
  }

  @protected
  CreateOrderRequest sse_decode_create_order_request(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_shipId = sse_decode_i_32(deserializer);
    var var_deliveryPort = sse_decode_opt_String(deserializer);
    var var_deliveryDate = sse_decode_opt_String(deserializer);
    var var_notes = sse_decode_opt_String(deserializer);
    var var_currency = sse_decode_String(deserializer);
    return CreateOrderRequest(
        shipId: var_shipId,
        deliveryPort: var_deliveryPort,
        deliveryDate: var_deliveryDate,
        notes: var_notes,
        currency: var_currency);
  }

  @protected
  CreateShipRequest sse_decode_create_ship_request(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_imoNumber = sse_decode_String(deserializer);
    var var_flag = sse_decode_String(deserializer);
    var var_shipType = sse_decode_opt_String(deserializer);
    var var_grossTonnage = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_owner = sse_decode_opt_String(deserializer);
    return CreateShipRequest(
        name: var_name,
        imoNumber: var_imoNumber,
        flag: var_flag,
        shipType: var_shipType,
        grossTonnage: var_grossTonnage,
        owner: var_owner);
  }

  @protected
  CreateSupplierRequest sse_decode_create_supplier_request(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_contactPerson = sse_decode_opt_String(deserializer);
    var var_email = sse_decode_opt_String(deserializer);
    var var_phone = sse_decode_opt_String(deserializer);
    var var_address = sse_decode_opt_String(deserializer);
    var var_country = sse_decode_opt_String(deserializer);
    var var_category = sse_decode_String(deserializer);
    return CreateSupplierRequest(
        name: var_name,
        contactPerson: var_contactPerson,
        email: var_email,
        phone: var_phone,
        address: var_address,
        country: var_country,
        category: var_category);
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  ItemProfit sse_decode_item_profit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_totalCost = sse_decode_f_64(deserializer);
    var var_totalRevenue = sse_decode_f_64(deserializer);
    var var_grossProfit = sse_decode_f_64(deserializer);
    var var_marginPercent = sse_decode_opt_box_autoadd_f_64(deserializer);
    return ItemProfit(
        totalCost: var_totalCost,
        totalRevenue: var_totalRevenue,
        grossProfit: var_grossProfit,
        marginPercent: var_marginPercent);
  }

  @protected
  List<Order> sse_decode_list_order(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Order>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_order(deserializer));
    }
    return ans_;
  }

  @protected
  List<OrderItem> sse_decode_list_order_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <OrderItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_order_item(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<Ship> sse_decode_list_ship(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Ship>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_ship(deserializer));
    }
    return ans_;
  }

  @protected
  List<Supplier> sse_decode_list_supplier(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Supplier>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_supplier(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  OrderStatus? sse_decode_opt_box_autoadd_order_status(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_order_status(deserializer));
    } else {
      return null;
    }
  }

  @protected
  OrderWithItems? sse_decode_opt_box_autoadd_order_with_items(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_order_with_items(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Ship? sse_decode_opt_box_autoadd_ship(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_ship(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Order sse_decode_order(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_32(deserializer);
    var var_orderNumber = sse_decode_String(deserializer);
    var var_shipId = sse_decode_i_32(deserializer);
    var var_shipName = sse_decode_opt_String(deserializer);
    var var_status = sse_decode_order_status(deserializer);
    var var_deliveryPort = sse_decode_opt_String(deserializer);
    var var_deliveryDate = sse_decode_opt_String(deserializer);
    var var_notes = sse_decode_opt_String(deserializer);
    var var_currency = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    var var_updatedAt = sse_decode_String(deserializer);
    return Order(
        id: var_id,
        orderNumber: var_orderNumber,
        shipId: var_shipId,
        shipName: var_shipName,
        status: var_status,
        deliveryPort: var_deliveryPort,
        deliveryDate: var_deliveryDate,
        notes: var_notes,
        currency: var_currency,
        createdAt: var_createdAt,
        updatedAt: var_updatedAt);
  }

  @protected
  OrderItem sse_decode_order_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_32(deserializer);
    var var_orderId = sse_decode_i_32(deserializer);
    var var_productName = sse_decode_String(deserializer);
    var var_impaCode = sse_decode_opt_String(deserializer);
    var var_description = sse_decode_opt_String(deserializer);
    var var_quantity = sse_decode_f_64(deserializer);
    var var_unit = sse_decode_String(deserializer);
    var var_buyingPrice = sse_decode_f_64(deserializer);
    var var_sellingPrice = sse_decode_f_64(deserializer);
    var var_currency = sse_decode_String(deserializer);
    var var_notes = sse_decode_opt_String(deserializer);
    return OrderItem(
        id: var_id,
        orderId: var_orderId,
        productName: var_productName,
        impaCode: var_impaCode,
        description: var_description,
        quantity: var_quantity,
        unit: var_unit,
        buyingPrice: var_buyingPrice,
        sellingPrice: var_sellingPrice,
        currency: var_currency,
        notes: var_notes);
  }

  @protected
  OrderStatus sse_decode_order_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return OrderStatus.values[inner];
  }

  @protected
  OrderTotals sse_decode_order_totals(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_itemCount = sse_decode_i_32(deserializer);
    var var_totalCost = sse_decode_f_64(deserializer);
    var var_totalRevenue = sse_decode_f_64(deserializer);
    var var_grossProfit = sse_decode_f_64(deserializer);
    var var_marginPercent = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_currency = sse_decode_String(deserializer);
    return OrderTotals(
        itemCount: var_itemCount,
        totalCost: var_totalCost,
        totalRevenue: var_totalRevenue,
        grossProfit: var_grossProfit,
        marginPercent: var_marginPercent,
        currency: var_currency);
  }

  @protected
  OrderWithItems sse_decode_order_with_items(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_order = sse_decode_order(deserializer);
    var var_items = sse_decode_list_order_item(deserializer);
    var var_totals = sse_decode_order_totals(deserializer);
    return OrderWithItems(
        order: var_order, items: var_items, totals: var_totals);
  }

  @protected
  Ship sse_decode_ship(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_32(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_imoNumber = sse_decode_String(deserializer);
    var var_flag = sse_decode_String(deserializer);
    var var_shipType = sse_decode_opt_String(deserializer);
    var var_grossTonnage = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_owner = sse_decode_opt_String(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    var var_updatedAt = sse_decode_String(deserializer);
    return Ship(
        id: var_id,
        name: var_name,
        imoNumber: var_imoNumber,
        flag: var_flag,
        shipType: var_shipType,
        grossTonnage: var_grossTonnage,
        owner: var_owner,
        createdAt: var_createdAt,
        updatedAt: var_updatedAt);
  }

  @protected
  Supplier sse_decode_supplier(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_32(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_contactPerson = sse_decode_opt_String(deserializer);
    var var_email = sse_decode_opt_String(deserializer);
    var var_phone = sse_decode_opt_String(deserializer);
    var var_address = sse_decode_opt_String(deserializer);
    var var_country = sse_decode_opt_String(deserializer);
    var var_category = sse_decode_String(deserializer);
    var var_isActive = sse_decode_bool(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    var var_updatedAt = sse_decode_String(deserializer);
    return Supplier(
        id: var_id,
        name: var_name,
        contactPerson: var_contactPerson,
        email: var_email,
        phone: var_phone,
        address: var_address,
        country: var_country,
        category: var_category,
        isActive: var_isActive,
        createdAt: var_createdAt,
        updatedAt: var_updatedAt);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  UpdateOrderItemRequest sse_decode_update_order_item_request(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_productName = sse_decode_opt_String(deserializer);
    var var_impaCode = sse_decode_opt_String(deserializer);
    var var_description = sse_decode_opt_String(deserializer);
    var var_quantity = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_unit = sse_decode_opt_String(deserializer);
    var var_buyingPrice = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_sellingPrice = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_notes = sse_decode_opt_String(deserializer);
    return UpdateOrderItemRequest(
        productName: var_productName,
        impaCode: var_impaCode,
        description: var_description,
        quantity: var_quantity,
        unit: var_unit,
        buyingPrice: var_buyingPrice,
        sellingPrice: var_sellingPrice,
        notes: var_notes);
  }

  @protected
  UpdateShipRequest sse_decode_update_ship_request(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_opt_String(deserializer);
    var var_imoNumber = sse_decode_opt_String(deserializer);
    var var_flag = sse_decode_opt_String(deserializer);
    var var_shipType = sse_decode_opt_String(deserializer);
    var var_grossTonnage = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_owner = sse_decode_opt_String(deserializer);
    return UpdateShipRequest(
        name: var_name,
        imoNumber: var_imoNumber,
        flag: var_flag,
        shipType: var_shipType,
        grossTonnage: var_grossTonnage,
        owner: var_owner);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_create_order_item_request(
      CreateOrderItemRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_create_order_item_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_create_order_request(
      CreateOrderRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_create_order_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_create_ship_request(
      CreateShipRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_create_ship_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_create_supplier_request(
      CreateSupplierRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_create_supplier_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_order_status(
      OrderStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_order_status(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_order_with_items(
      OrderWithItems self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_order_with_items(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_ship(Ship self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ship(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_update_order_item_request(
      UpdateOrderItemRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_update_order_item_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_update_ship_request(
      UpdateShipRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_update_ship_request(self, serializer);
  }

  @protected
  void sse_encode_create_order_item_request(
      CreateOrderItemRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.orderId, serializer);
    sse_encode_String(self.productName, serializer);
    sse_encode_opt_String(self.impaCode, serializer);
    sse_encode_opt_String(self.description, serializer);
    sse_encode_f_64(self.quantity, serializer);
    sse_encode_String(self.unit, serializer);
    sse_encode_f_64(self.buyingPrice, serializer);
    sse_encode_f_64(self.sellingPrice, serializer);
    sse_encode_String(self.currency, serializer);
    sse_encode_opt_String(self.notes, serializer);
  }

  @protected
  void sse_encode_create_order_request(
      CreateOrderRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.shipId, serializer);
    sse_encode_opt_String(self.deliveryPort, serializer);
    sse_encode_opt_String(self.deliveryDate, serializer);
    sse_encode_opt_String(self.notes, serializer);
    sse_encode_String(self.currency, serializer);
  }

  @protected
  void sse_encode_create_ship_request(
      CreateShipRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.imoNumber, serializer);
    sse_encode_String(self.flag, serializer);
    sse_encode_opt_String(self.shipType, serializer);
    sse_encode_opt_box_autoadd_f_64(self.grossTonnage, serializer);
    sse_encode_opt_String(self.owner, serializer);
  }

  @protected
  void sse_encode_create_supplier_request(
      CreateSupplierRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_opt_String(self.contactPerson, serializer);
    sse_encode_opt_String(self.email, serializer);
    sse_encode_opt_String(self.phone, serializer);
    sse_encode_opt_String(self.address, serializer);
    sse_encode_opt_String(self.country, serializer);
    sse_encode_String(self.category, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_item_profit(ItemProfit self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.totalCost, serializer);
    sse_encode_f_64(self.totalRevenue, serializer);
    sse_encode_f_64(self.grossProfit, serializer);
    sse_encode_opt_box_autoadd_f_64(self.marginPercent, serializer);
  }

  @protected
  void sse_encode_list_order(List<Order> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_order(item, serializer);
    }
  }

  @protected
  void sse_encode_list_order_item(
      List<OrderItem> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_order_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_ship(List<Ship> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_ship(item, serializer);
    }
  }

  @protected
  void sse_encode_list_supplier(List<Supplier> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_supplier(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_order_status(
      OrderStatus? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_order_status(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_order_with_items(
      OrderWithItems? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_order_with_items(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_ship(Ship? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_ship(self, serializer);
    }
  }

  @protected
  void sse_encode_order(Order self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.id, serializer);
    sse_encode_String(self.orderNumber, serializer);
    sse_encode_i_32(self.shipId, serializer);
    sse_encode_opt_String(self.shipName, serializer);
    sse_encode_order_status(self.status, serializer);
    sse_encode_opt_String(self.deliveryPort, serializer);
    sse_encode_opt_String(self.deliveryDate, serializer);
    sse_encode_opt_String(self.notes, serializer);
    sse_encode_String(self.currency, serializer);
    sse_encode_String(self.createdAt, serializer);
    sse_encode_String(self.updatedAt, serializer);
  }

  @protected
  void sse_encode_order_item(OrderItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.id, serializer);
    sse_encode_i_32(self.orderId, serializer);
    sse_encode_String(self.productName, serializer);
    sse_encode_opt_String(self.impaCode, serializer);
    sse_encode_opt_String(self.description, serializer);
    sse_encode_f_64(self.quantity, serializer);
    sse_encode_String(self.unit, serializer);
    sse_encode_f_64(self.buyingPrice, serializer);
    sse_encode_f_64(self.sellingPrice, serializer);
    sse_encode_String(self.currency, serializer);
    sse_encode_opt_String(self.notes, serializer);
  }

  @protected
  void sse_encode_order_status(OrderStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_order_totals(OrderTotals self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.itemCount, serializer);
    sse_encode_f_64(self.totalCost, serializer);
    sse_encode_f_64(self.totalRevenue, serializer);
    sse_encode_f_64(self.grossProfit, serializer);
    sse_encode_opt_box_autoadd_f_64(self.marginPercent, serializer);
    sse_encode_String(self.currency, serializer);
  }

  @protected
  void sse_encode_order_with_items(
      OrderWithItems self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_order(self.order, serializer);
    sse_encode_list_order_item(self.items, serializer);
    sse_encode_order_totals(self.totals, serializer);
  }

  @protected
  void sse_encode_ship(Ship self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.imoNumber, serializer);
    sse_encode_String(self.flag, serializer);
    sse_encode_opt_String(self.shipType, serializer);
    sse_encode_opt_box_autoadd_f_64(self.grossTonnage, serializer);
    sse_encode_opt_String(self.owner, serializer);
    sse_encode_String(self.createdAt, serializer);
    sse_encode_String(self.updatedAt, serializer);
  }

  @protected
  void sse_encode_supplier(Supplier self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_opt_String(self.contactPerson, serializer);
    sse_encode_opt_String(self.email, serializer);
    sse_encode_opt_String(self.phone, serializer);
    sse_encode_opt_String(self.address, serializer);
    sse_encode_opt_String(self.country, serializer);
    sse_encode_String(self.category, serializer);
    sse_encode_bool(self.isActive, serializer);
    sse_encode_String(self.createdAt, serializer);
    sse_encode_String(self.updatedAt, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_update_order_item_request(
      UpdateOrderItemRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.productName, serializer);
    sse_encode_opt_String(self.impaCode, serializer);
    sse_encode_opt_String(self.description, serializer);
    sse_encode_opt_box_autoadd_f_64(self.quantity, serializer);
    sse_encode_opt_String(self.unit, serializer);
    sse_encode_opt_box_autoadd_f_64(self.buyingPrice, serializer);
    sse_encode_opt_box_autoadd_f_64(self.sellingPrice, serializer);
    sse_encode_opt_String(self.notes, serializer);
  }

  @protected
  void sse_encode_update_ship_request(
      UpdateShipRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.name, serializer);
    sse_encode_opt_String(self.imoNumber, serializer);
    sse_encode_opt_String(self.flag, serializer);
    sse_encode_opt_String(self.shipType, serializer);
    sse_encode_opt_box_autoadd_f_64(self.grossTonnage, serializer);
    sse_encode_opt_String(self.owner, serializer);
  }
}
