// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class CreateOrderItemRequest {
  final int orderId;
  final String productName;
  final String? impaCode;
  final String? description;
  final double quantity;
  final String unit;
  final double buyingPrice;
  final double sellingPrice;
  final String currency;
  final DeliveryType deliveryType;
  final String? warehouseDeliveryDate;
  final String? shipDeliveryDate;
  final String? notes;

  const CreateOrderItemRequest({
    required this.orderId,
    required this.productName,
    this.impaCode,
    this.description,
    required this.quantity,
    required this.unit,
    required this.buyingPrice,
    required this.sellingPrice,
    required this.currency,
    required this.deliveryType,
    this.warehouseDeliveryDate,
    this.shipDeliveryDate,
    this.notes,
  });

  @override
  int get hashCode =>
      orderId.hashCode ^
      productName.hashCode ^
      impaCode.hashCode ^
      description.hashCode ^
      quantity.hashCode ^
      unit.hashCode ^
      buyingPrice.hashCode ^
      sellingPrice.hashCode ^
      currency.hashCode ^
      deliveryType.hashCode ^
      warehouseDeliveryDate.hashCode ^
      shipDeliveryDate.hashCode ^
      notes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreateOrderItemRequest &&
          runtimeType == other.runtimeType &&
          orderId == other.orderId &&
          productName == other.productName &&
          impaCode == other.impaCode &&
          description == other.description &&
          quantity == other.quantity &&
          unit == other.unit &&
          buyingPrice == other.buyingPrice &&
          sellingPrice == other.sellingPrice &&
          currency == other.currency &&
          deliveryType == other.deliveryType &&
          warehouseDeliveryDate == other.warehouseDeliveryDate &&
          shipDeliveryDate == other.shipDeliveryDate &&
          notes == other.notes;
}

class CreateOrderRequest {
  final int shipId;
  final String? deliveryPort;
  final String? notes;
  final String currency;

  const CreateOrderRequest({
    required this.shipId,
    this.deliveryPort,
    this.notes,
    required this.currency,
  });

  @override
  int get hashCode =>
      shipId.hashCode ^
      deliveryPort.hashCode ^
      notes.hashCode ^
      currency.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreateOrderRequest &&
          runtimeType == other.runtimeType &&
          shipId == other.shipId &&
          deliveryPort == other.deliveryPort &&
          notes == other.notes &&
          currency == other.currency;
}

class CreateShipRequest {
  final String name;
  final String imoNumber;
  final String flag;
  final String? shipType;
  final double? grossTonnage;
  final String? owner;

  const CreateShipRequest({
    required this.name,
    required this.imoNumber,
    required this.flag,
    this.shipType,
    this.grossTonnage,
    this.owner,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      imoNumber.hashCode ^
      flag.hashCode ^
      shipType.hashCode ^
      grossTonnage.hashCode ^
      owner.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreateShipRequest &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          imoNumber == other.imoNumber &&
          flag == other.flag &&
          shipType == other.shipType &&
          grossTonnage == other.grossTonnage &&
          owner == other.owner;
}

class CreateSupplierRequest {
  final String name;
  final String? contactPerson;
  final String? email;
  final String? phone;
  final String? address;
  final String? country;
  final String category;

  const CreateSupplierRequest({
    required this.name,
    this.contactPerson,
    this.email,
    this.phone,
    this.address,
    this.country,
    required this.category,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      contactPerson.hashCode ^
      email.hashCode ^
      phone.hashCode ^
      address.hashCode ^
      country.hashCode ^
      category.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreateSupplierRequest &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          contactPerson == other.contactPerson &&
          email == other.email &&
          phone == other.phone &&
          address == other.address &&
          country == other.country &&
          category == other.category;
}

class CreateSupplyItemRequest {
  final int supplierId;
  final String? impaCode;
  final String name;
  final String? description;
  final String category;
  final String unit;
  final double unitPrice;
  final String currency;
  final int? minimumOrderQuantity;

  const CreateSupplyItemRequest({
    required this.supplierId,
    this.impaCode,
    required this.name,
    this.description,
    required this.category,
    required this.unit,
    required this.unitPrice,
    required this.currency,
    this.minimumOrderQuantity,
  });

  @override
  int get hashCode =>
      supplierId.hashCode ^
      impaCode.hashCode ^
      name.hashCode ^
      description.hashCode ^
      category.hashCode ^
      unit.hashCode ^
      unitPrice.hashCode ^
      currency.hashCode ^
      minimumOrderQuantity.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreateSupplyItemRequest &&
          runtimeType == other.runtimeType &&
          supplierId == other.supplierId &&
          impaCode == other.impaCode &&
          name == other.name &&
          description == other.description &&
          category == other.category &&
          unit == other.unit &&
          unitPrice == other.unitPrice &&
          currency == other.currency &&
          minimumOrderQuantity == other.minimumOrderQuantity;
}

/// Delivery type - how the order will be delivered
enum DeliveryType {
  /// Supplier -> Warehouse -> Ship
  viaWarehouse,

  /// Supplier -> Ship (direct delivery)
  directToShip,
  ;
}

/// Profit calculation for a single item
class ItemProfit {
  /// Total cost: buying_price * quantity
  final double totalCost;

  /// Total revenue: selling_price * quantity
  final double totalRevenue;

  /// Gross profit: (selling_price - buying_price) * quantity
  final double grossProfit;

  /// Margin percentage: ((selling_price - buying_price) / selling_price) * 100
  final double? marginPercent;

  const ItemProfit({
    required this.totalCost,
    required this.totalRevenue,
    required this.grossProfit,
    this.marginPercent,
  });

  @override
  int get hashCode =>
      totalCost.hashCode ^
      totalRevenue.hashCode ^
      grossProfit.hashCode ^
      marginPercent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ItemProfit &&
          runtimeType == other.runtimeType &&
          totalCost == other.totalCost &&
          totalRevenue == other.totalRevenue &&
          grossProfit == other.grossProfit &&
          marginPercent == other.marginPercent;
}

class Order {
  final int id;
  final String orderNumber;
  final int shipId;
  final String? shipName;
  final OrderStatus status;
  final String? deliveryPort;
  final String? notes;
  final String currency;
  final String createdAt;
  final String updatedAt;

  const Order({
    required this.id,
    required this.orderNumber,
    required this.shipId,
    this.shipName,
    required this.status,
    this.deliveryPort,
    this.notes,
    required this.currency,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      orderNumber.hashCode ^
      shipId.hashCode ^
      shipName.hashCode ^
      status.hashCode ^
      deliveryPort.hashCode ^
      notes.hashCode ^
      currency.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Order &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          orderNumber == other.orderNumber &&
          shipId == other.shipId &&
          shipName == other.shipName &&
          status == other.status &&
          deliveryPort == other.deliveryPort &&
          notes == other.notes &&
          currency == other.currency &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

class OrderItem {
  final int id;
  final int orderId;
  final String productName;
  final String? impaCode;
  final String? description;
  final double quantity;
  final String unit;

  /// Cost price - what we pay to supplier
  final double buyingPrice;

  /// Revenue price - what we charge the customer
  final double sellingPrice;
  final String currency;

  /// Delivery type for this item
  final DeliveryType deliveryType;

  /// When supplier delivers to warehouse (if ViaWarehouse)
  final String? warehouseDeliveryDate;

  /// When delivered to ship
  final String? shipDeliveryDate;
  final String? notes;

  const OrderItem({
    required this.id,
    required this.orderId,
    required this.productName,
    this.impaCode,
    this.description,
    required this.quantity,
    required this.unit,
    required this.buyingPrice,
    required this.sellingPrice,
    required this.currency,
    required this.deliveryType,
    this.warehouseDeliveryDate,
    this.shipDeliveryDate,
    this.notes,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      orderId.hashCode ^
      productName.hashCode ^
      impaCode.hashCode ^
      description.hashCode ^
      quantity.hashCode ^
      unit.hashCode ^
      buyingPrice.hashCode ^
      sellingPrice.hashCode ^
      currency.hashCode ^
      deliveryType.hashCode ^
      warehouseDeliveryDate.hashCode ^
      shipDeliveryDate.hashCode ^
      notes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OrderItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          orderId == other.orderId &&
          productName == other.productName &&
          impaCode == other.impaCode &&
          description == other.description &&
          quantity == other.quantity &&
          unit == other.unit &&
          buyingPrice == other.buyingPrice &&
          sellingPrice == other.sellingPrice &&
          currency == other.currency &&
          deliveryType == other.deliveryType &&
          warehouseDeliveryDate == other.warehouseDeliveryDate &&
          shipDeliveryDate == other.shipDeliveryDate &&
          notes == other.notes;
}

/// Order Status - Enforced state machine flow
/// NEW -> QUOTED -> AGREED -> WAITING_GOODS -> PREPARED -> ON_WAY -> DELIVERED -> INVOICED
enum OrderStatus {
  new_,
  quoted,
  agreed,
  waitingGoods,
  prepared,
  onWay,
  delivered,
  invoiced,
  cancelled,
  ;
}

/// Order totals calculated in Rust
class OrderTotals {
  final int itemCount;
  final double totalCost;
  final double totalRevenue;
  final double grossProfit;
  final double? marginPercent;
  final String currency;

  const OrderTotals({
    required this.itemCount,
    required this.totalCost,
    required this.totalRevenue,
    required this.grossProfit,
    this.marginPercent,
    required this.currency,
  });

  @override
  int get hashCode =>
      itemCount.hashCode ^
      totalCost.hashCode ^
      totalRevenue.hashCode ^
      grossProfit.hashCode ^
      marginPercent.hashCode ^
      currency.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OrderTotals &&
          runtimeType == other.runtimeType &&
          itemCount == other.itemCount &&
          totalCost == other.totalCost &&
          totalRevenue == other.totalRevenue &&
          grossProfit == other.grossProfit &&
          marginPercent == other.marginPercent &&
          currency == other.currency;
}

class OrderWithItems {
  final Order order;
  final List<OrderItem> items;
  final OrderTotals totals;

  const OrderWithItems({
    required this.order,
    required this.items,
    required this.totals,
  });

  @override
  int get hashCode => order.hashCode ^ items.hashCode ^ totals.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OrderWithItems &&
          runtimeType == other.runtimeType &&
          order == other.order &&
          items == other.items &&
          totals == other.totals;
}

class Ship {
  final int id;
  final String name;
  final String imoNumber;
  final String flag;
  final String? shipType;
  final double? grossTonnage;
  final String? owner;
  final String createdAt;
  final String updatedAt;

  const Ship({
    required this.id,
    required this.name,
    required this.imoNumber,
    required this.flag,
    this.shipType,
    this.grossTonnage,
    this.owner,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      imoNumber.hashCode ^
      flag.hashCode ^
      shipType.hashCode ^
      grossTonnage.hashCode ^
      owner.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Ship &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          imoNumber == other.imoNumber &&
          flag == other.flag &&
          shipType == other.shipType &&
          grossTonnage == other.grossTonnage &&
          owner == other.owner &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

class Supplier {
  final int id;
  final String name;
  final String? contactPerson;
  final String? email;
  final String? phone;
  final String? address;
  final String? country;
  final String category;
  final bool isActive;
  final String createdAt;
  final String updatedAt;

  const Supplier({
    required this.id,
    required this.name,
    this.contactPerson,
    this.email,
    this.phone,
    this.address,
    this.country,
    required this.category,
    required this.isActive,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      contactPerson.hashCode ^
      email.hashCode ^
      phone.hashCode ^
      address.hashCode ^
      country.hashCode ^
      category.hashCode ^
      isActive.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Supplier &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          contactPerson == other.contactPerson &&
          email == other.email &&
          phone == other.phone &&
          address == other.address &&
          country == other.country &&
          category == other.category &&
          isActive == other.isActive &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

class SupplyItem {
  final int id;
  final int supplierId;
  final String? supplierName;
  final String? impaCode;
  final String name;
  final String? description;
  final String category;
  final String unit;
  final double unitPrice;
  final String currency;
  final int? minimumOrderQuantity;
  final bool isAvailable;
  final String createdAt;
  final String updatedAt;

  const SupplyItem({
    required this.id,
    required this.supplierId,
    this.supplierName,
    this.impaCode,
    required this.name,
    this.description,
    required this.category,
    required this.unit,
    required this.unitPrice,
    required this.currency,
    this.minimumOrderQuantity,
    required this.isAvailable,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      supplierId.hashCode ^
      supplierName.hashCode ^
      impaCode.hashCode ^
      name.hashCode ^
      description.hashCode ^
      category.hashCode ^
      unit.hashCode ^
      unitPrice.hashCode ^
      currency.hashCode ^
      minimumOrderQuantity.hashCode ^
      isAvailable.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SupplyItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          supplierId == other.supplierId &&
          supplierName == other.supplierName &&
          impaCode == other.impaCode &&
          name == other.name &&
          description == other.description &&
          category == other.category &&
          unit == other.unit &&
          unitPrice == other.unitPrice &&
          currency == other.currency &&
          minimumOrderQuantity == other.minimumOrderQuantity &&
          isAvailable == other.isAvailable &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

class UpdateOrderItemRequest {
  final String? productName;
  final String? impaCode;
  final String? description;
  final double? quantity;
  final String? unit;
  final double? buyingPrice;
  final double? sellingPrice;
  final DeliveryType? deliveryType;
  final String? warehouseDeliveryDate;
  final String? shipDeliveryDate;
  final String? notes;

  const UpdateOrderItemRequest({
    this.productName,
    this.impaCode,
    this.description,
    this.quantity,
    this.unit,
    this.buyingPrice,
    this.sellingPrice,
    this.deliveryType,
    this.warehouseDeliveryDate,
    this.shipDeliveryDate,
    this.notes,
  });

  @override
  int get hashCode =>
      productName.hashCode ^
      impaCode.hashCode ^
      description.hashCode ^
      quantity.hashCode ^
      unit.hashCode ^
      buyingPrice.hashCode ^
      sellingPrice.hashCode ^
      deliveryType.hashCode ^
      warehouseDeliveryDate.hashCode ^
      shipDeliveryDate.hashCode ^
      notes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateOrderItemRequest &&
          runtimeType == other.runtimeType &&
          productName == other.productName &&
          impaCode == other.impaCode &&
          description == other.description &&
          quantity == other.quantity &&
          unit == other.unit &&
          buyingPrice == other.buyingPrice &&
          sellingPrice == other.sellingPrice &&
          deliveryType == other.deliveryType &&
          warehouseDeliveryDate == other.warehouseDeliveryDate &&
          shipDeliveryDate == other.shipDeliveryDate &&
          notes == other.notes;
}

class UpdateShipRequest {
  final String? name;
  final String? imoNumber;
  final String? flag;
  final String? shipType;
  final double? grossTonnage;
  final String? owner;

  const UpdateShipRequest({
    this.name,
    this.imoNumber,
    this.flag,
    this.shipType,
    this.grossTonnage,
    this.owner,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      imoNumber.hashCode ^
      flag.hashCode ^
      shipType.hashCode ^
      grossTonnage.hashCode ^
      owner.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateShipRequest &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          imoNumber == other.imoNumber &&
          flag == other.flag &&
          shipType == other.shipType &&
          grossTonnage == other.grossTonnage &&
          owner == other.owner;
}

class UpdateSupplierRequest {
  final String? name;
  final String? contactPerson;
  final String? email;
  final String? phone;
  final String? address;
  final String? country;
  final String? category;

  const UpdateSupplierRequest({
    this.name,
    this.contactPerson,
    this.email,
    this.phone,
    this.address,
    this.country,
    this.category,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      contactPerson.hashCode ^
      email.hashCode ^
      phone.hashCode ^
      address.hashCode ^
      country.hashCode ^
      category.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateSupplierRequest &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          contactPerson == other.contactPerson &&
          email == other.email &&
          phone == other.phone &&
          address == other.address &&
          country == other.country &&
          category == other.category;
}

class UpdateSupplyItemRequest {
  final int? supplierId;
  final String? impaCode;
  final String? name;
  final String? description;
  final String? category;
  final String? unit;
  final double? unitPrice;
  final String? currency;
  final int? minimumOrderQuantity;
  final bool? isAvailable;

  const UpdateSupplyItemRequest({
    this.supplierId,
    this.impaCode,
    this.name,
    this.description,
    this.category,
    this.unit,
    this.unitPrice,
    this.currency,
    this.minimumOrderQuantity,
    this.isAvailable,
  });

  @override
  int get hashCode =>
      supplierId.hashCode ^
      impaCode.hashCode ^
      name.hashCode ^
      description.hashCode ^
      category.hashCode ^
      unit.hashCode ^
      unitPrice.hashCode ^
      currency.hashCode ^
      minimumOrderQuantity.hashCode ^
      isAvailable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateSupplyItemRequest &&
          runtimeType == other.runtimeType &&
          supplierId == other.supplierId &&
          impaCode == other.impaCode &&
          name == other.name &&
          description == other.description &&
          category == other.category &&
          unit == other.unit &&
          unitPrice == other.unitPrice &&
          currency == other.currency &&
          minimumOrderQuantity == other.minimumOrderQuantity &&
          isAvailable == other.isAvailable;
}
