// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Calendar data response with all events
class CalendarData {
  final List<CalendarEvent> events;
  final List<Port> ports;

  const CalendarData({
    required this.events,
    required this.ports,
  });

  @override
  int get hashCode => events.hashCode ^ ports.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CalendarData &&
          runtimeType == other.runtimeType &&
          events == other.events &&
          ports == other.ports;
}

/// Calendar event for unified calendar view
class CalendarEvent {
  final String id;
  final CalendarEventType eventType;
  final String title;
  final String? subtitle;
  final String startDate;
  final String endDate;
  final String color;
  final String status;
  final int? relatedShipId;
  final int? relatedPortId;
  final int? relatedOrderId;
  final String? metadata;

  const CalendarEvent({
    required this.id,
    required this.eventType,
    required this.title,
    this.subtitle,
    required this.startDate,
    required this.endDate,
    required this.color,
    required this.status,
    this.relatedShipId,
    this.relatedPortId,
    this.relatedOrderId,
    this.metadata,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      eventType.hashCode ^
      title.hashCode ^
      subtitle.hashCode ^
      startDate.hashCode ^
      endDate.hashCode ^
      color.hashCode ^
      status.hashCode ^
      relatedShipId.hashCode ^
      relatedPortId.hashCode ^
      relatedOrderId.hashCode ^
      metadata.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CalendarEvent &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          eventType == other.eventType &&
          title == other.title &&
          subtitle == other.subtitle &&
          startDate == other.startDate &&
          endDate == other.endDate &&
          color == other.color &&
          status == other.status &&
          relatedShipId == other.relatedShipId &&
          relatedPortId == other.relatedPortId &&
          relatedOrderId == other.relatedOrderId &&
          metadata == other.metadata;
}

/// Calendar event type
enum CalendarEventType {
  shipVisit,
  orderDelivery,
  warehouseDelivery,
  shipDelivery,
  ;
}

class CreateOrderItemRequest {
  final int orderId;
  final String productName;
  final String? impaCode;
  final String? description;
  final double quantity;
  final String unit;
  final double buyingPrice;
  final double sellingPrice;
  final String currency;
  final DeliveryType deliveryType;
  final String? warehouseDeliveryDate;
  final String? shipDeliveryDate;
  final String? notes;

  const CreateOrderItemRequest({
    required this.orderId,
    required this.productName,
    this.impaCode,
    this.description,
    required this.quantity,
    required this.unit,
    required this.buyingPrice,
    required this.sellingPrice,
    required this.currency,
    required this.deliveryType,
    this.warehouseDeliveryDate,
    this.shipDeliveryDate,
    this.notes,
  });

  @override
  int get hashCode =>
      orderId.hashCode ^
      productName.hashCode ^
      impaCode.hashCode ^
      description.hashCode ^
      quantity.hashCode ^
      unit.hashCode ^
      buyingPrice.hashCode ^
      sellingPrice.hashCode ^
      currency.hashCode ^
      deliveryType.hashCode ^
      warehouseDeliveryDate.hashCode ^
      shipDeliveryDate.hashCode ^
      notes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreateOrderItemRequest &&
          runtimeType == other.runtimeType &&
          orderId == other.orderId &&
          productName == other.productName &&
          impaCode == other.impaCode &&
          description == other.description &&
          quantity == other.quantity &&
          unit == other.unit &&
          buyingPrice == other.buyingPrice &&
          sellingPrice == other.sellingPrice &&
          currency == other.currency &&
          deliveryType == other.deliveryType &&
          warehouseDeliveryDate == other.warehouseDeliveryDate &&
          shipDeliveryDate == other.shipDeliveryDate &&
          notes == other.notes;
}

class CreateOrderRequest {
  final int shipId;
  final String? deliveryPort;
  final String? notes;
  final String currency;

  const CreateOrderRequest({
    required this.shipId,
    this.deliveryPort,
    this.notes,
    required this.currency,
  });

  @override
  int get hashCode =>
      shipId.hashCode ^
      deliveryPort.hashCode ^
      notes.hashCode ^
      currency.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreateOrderRequest &&
          runtimeType == other.runtimeType &&
          shipId == other.shipId &&
          deliveryPort == other.deliveryPort &&
          notes == other.notes &&
          currency == other.currency;
}

class CreatePortRequest {
  final String name;
  final String country;
  final String? city;
  final String timezone;
  final double? latitude;
  final double? longitude;
  final String? notes;

  const CreatePortRequest({
    required this.name,
    required this.country,
    this.city,
    required this.timezone,
    this.latitude,
    this.longitude,
    this.notes,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      country.hashCode ^
      city.hashCode ^
      timezone.hashCode ^
      latitude.hashCode ^
      longitude.hashCode ^
      notes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreatePortRequest &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          country == other.country &&
          city == other.city &&
          timezone == other.timezone &&
          latitude == other.latitude &&
          longitude == other.longitude &&
          notes == other.notes;
}

class CreateShipRequest {
  final String name;
  final String imoNumber;
  final String flag;
  final String? shipType;
  final double? grossTonnage;
  final String? owner;

  const CreateShipRequest({
    required this.name,
    required this.imoNumber,
    required this.flag,
    this.shipType,
    this.grossTonnage,
    this.owner,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      imoNumber.hashCode ^
      flag.hashCode ^
      shipType.hashCode ^
      grossTonnage.hashCode ^
      owner.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreateShipRequest &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          imoNumber == other.imoNumber &&
          flag == other.flag &&
          shipType == other.shipType &&
          grossTonnage == other.grossTonnage &&
          owner == other.owner;
}

class CreateShipVisitRequest {
  final int shipId;
  final int portId;
  final String eta;
  final String etd;
  final String? agentInfo;
  final String? notes;

  const CreateShipVisitRequest({
    required this.shipId,
    required this.portId,
    required this.eta,
    required this.etd,
    this.agentInfo,
    this.notes,
  });

  @override
  int get hashCode =>
      shipId.hashCode ^
      portId.hashCode ^
      eta.hashCode ^
      etd.hashCode ^
      agentInfo.hashCode ^
      notes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreateShipVisitRequest &&
          runtimeType == other.runtimeType &&
          shipId == other.shipId &&
          portId == other.portId &&
          eta == other.eta &&
          etd == other.etd &&
          agentInfo == other.agentInfo &&
          notes == other.notes;
}

class CreateStockMovementRequest {
  final int stockId;
  final StockMovementType movementType;
  final double quantity;
  final String? referenceType;
  final int? referenceId;
  final String? referenceInfo;
  final String? notes;

  const CreateStockMovementRequest({
    required this.stockId,
    required this.movementType,
    required this.quantity,
    this.referenceType,
    this.referenceId,
    this.referenceInfo,
    this.notes,
  });

  @override
  int get hashCode =>
      stockId.hashCode ^
      movementType.hashCode ^
      quantity.hashCode ^
      referenceType.hashCode ^
      referenceId.hashCode ^
      referenceInfo.hashCode ^
      notes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreateStockMovementRequest &&
          runtimeType == other.runtimeType &&
          stockId == other.stockId &&
          movementType == other.movementType &&
          quantity == other.quantity &&
          referenceType == other.referenceType &&
          referenceId == other.referenceId &&
          referenceInfo == other.referenceInfo &&
          notes == other.notes;
}

class CreateStockRequest {
  final int supplyItemId;
  final double quantity;
  final String unit;
  final String? warehouseLocation;
  final double minimumQuantity;

  const CreateStockRequest({
    required this.supplyItemId,
    required this.quantity,
    required this.unit,
    this.warehouseLocation,
    required this.minimumQuantity,
  });

  @override
  int get hashCode =>
      supplyItemId.hashCode ^
      quantity.hashCode ^
      unit.hashCode ^
      warehouseLocation.hashCode ^
      minimumQuantity.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreateStockRequest &&
          runtimeType == other.runtimeType &&
          supplyItemId == other.supplyItemId &&
          quantity == other.quantity &&
          unit == other.unit &&
          warehouseLocation == other.warehouseLocation &&
          minimumQuantity == other.minimumQuantity;
}

class CreateSupplierRequest {
  final String name;
  final String? contactPerson;
  final String? email;
  final String? phone;
  final String? address;
  final String? country;
  final String category;

  const CreateSupplierRequest({
    required this.name,
    this.contactPerson,
    this.email,
    this.phone,
    this.address,
    this.country,
    required this.category,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      contactPerson.hashCode ^
      email.hashCode ^
      phone.hashCode ^
      address.hashCode ^
      country.hashCode ^
      category.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreateSupplierRequest &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          contactPerson == other.contactPerson &&
          email == other.email &&
          phone == other.phone &&
          address == other.address &&
          country == other.country &&
          category == other.category;
}

class CreateSupplyItemRequest {
  final int supplierId;
  final String? impaCode;
  final String name;
  final String? description;
  final String category;
  final String unit;
  final double unitPrice;
  final String currency;
  final int? minimumOrderQuantity;

  const CreateSupplyItemRequest({
    required this.supplierId,
    this.impaCode,
    required this.name,
    this.description,
    required this.category,
    required this.unit,
    required this.unitPrice,
    required this.currency,
    this.minimumOrderQuantity,
  });

  @override
  int get hashCode =>
      supplierId.hashCode ^
      impaCode.hashCode ^
      name.hashCode ^
      description.hashCode ^
      category.hashCode ^
      unit.hashCode ^
      unitPrice.hashCode ^
      currency.hashCode ^
      minimumOrderQuantity.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreateSupplyItemRequest &&
          runtimeType == other.runtimeType &&
          supplierId == other.supplierId &&
          impaCode == other.impaCode &&
          name == other.name &&
          description == other.description &&
          category == other.category &&
          unit == other.unit &&
          unitPrice == other.unitPrice &&
          currency == other.currency &&
          minimumOrderQuantity == other.minimumOrderQuantity;
}

/// Delivery type - how the order will be delivered
enum DeliveryType {
  /// Supplier -> Warehouse -> Ship
  viaWarehouse,

  /// Supplier -> Ship (direct delivery)
  directToShip,
  ;
}

/// Profit calculation for a single item
class ItemProfit {
  /// Total cost: buying_price * quantity
  final double totalCost;

  /// Total revenue: selling_price * quantity
  final double totalRevenue;

  /// Gross profit: (selling_price - buying_price) * quantity
  final double grossProfit;

  /// Margin percentage: ((selling_price - buying_price) / selling_price) * 100
  final double? marginPercent;

  const ItemProfit({
    required this.totalCost,
    required this.totalRevenue,
    required this.grossProfit,
    this.marginPercent,
  });

  @override
  int get hashCode =>
      totalCost.hashCode ^
      totalRevenue.hashCode ^
      grossProfit.hashCode ^
      marginPercent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ItemProfit &&
          runtimeType == other.runtimeType &&
          totalCost == other.totalCost &&
          totalRevenue == other.totalRevenue &&
          grossProfit == other.grossProfit &&
          marginPercent == other.marginPercent;
}

class Order {
  final int id;
  final String orderNumber;
  final int shipId;
  final String? shipName;
  final OrderStatus status;
  final String? deliveryPort;
  final String? notes;
  final String currency;
  final String createdAt;
  final String updatedAt;

  const Order({
    required this.id,
    required this.orderNumber,
    required this.shipId,
    this.shipName,
    required this.status,
    this.deliveryPort,
    this.notes,
    required this.currency,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      orderNumber.hashCode ^
      shipId.hashCode ^
      shipName.hashCode ^
      status.hashCode ^
      deliveryPort.hashCode ^
      notes.hashCode ^
      currency.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Order &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          orderNumber == other.orderNumber &&
          shipId == other.shipId &&
          shipName == other.shipName &&
          status == other.status &&
          deliveryPort == other.deliveryPort &&
          notes == other.notes &&
          currency == other.currency &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

class OrderItem {
  final int id;
  final int orderId;
  final String productName;
  final String? impaCode;
  final String? description;
  final double quantity;
  final String unit;

  /// Cost price - what we pay to supplier
  final double buyingPrice;

  /// Revenue price - what we charge the customer
  final double sellingPrice;
  final String currency;

  /// Delivery type for this item
  final DeliveryType deliveryType;

  /// When supplier delivers to warehouse (if ViaWarehouse)
  final String? warehouseDeliveryDate;

  /// When delivered to ship
  final String? shipDeliveryDate;
  final String? notes;

  const OrderItem({
    required this.id,
    required this.orderId,
    required this.productName,
    this.impaCode,
    this.description,
    required this.quantity,
    required this.unit,
    required this.buyingPrice,
    required this.sellingPrice,
    required this.currency,
    required this.deliveryType,
    this.warehouseDeliveryDate,
    this.shipDeliveryDate,
    this.notes,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      orderId.hashCode ^
      productName.hashCode ^
      impaCode.hashCode ^
      description.hashCode ^
      quantity.hashCode ^
      unit.hashCode ^
      buyingPrice.hashCode ^
      sellingPrice.hashCode ^
      currency.hashCode ^
      deliveryType.hashCode ^
      warehouseDeliveryDate.hashCode ^
      shipDeliveryDate.hashCode ^
      notes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OrderItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          orderId == other.orderId &&
          productName == other.productName &&
          impaCode == other.impaCode &&
          description == other.description &&
          quantity == other.quantity &&
          unit == other.unit &&
          buyingPrice == other.buyingPrice &&
          sellingPrice == other.sellingPrice &&
          currency == other.currency &&
          deliveryType == other.deliveryType &&
          warehouseDeliveryDate == other.warehouseDeliveryDate &&
          shipDeliveryDate == other.shipDeliveryDate &&
          notes == other.notes;
}

/// Order Status - Enforced state machine flow
/// NEW -> QUOTED -> AGREED -> WAITING_GOODS -> PREPARED -> ON_WAY -> DELIVERED -> INVOICED
enum OrderStatus {
  new_,
  quoted,
  agreed,
  waitingGoods,
  prepared,
  onWay,
  delivered,
  invoiced,
  cancelled,
  ;
}

/// Order totals calculated in Rust
class OrderTotals {
  final int itemCount;
  final double totalCost;
  final double totalRevenue;
  final double grossProfit;
  final double? marginPercent;
  final String currency;

  const OrderTotals({
    required this.itemCount,
    required this.totalCost,
    required this.totalRevenue,
    required this.grossProfit,
    this.marginPercent,
    required this.currency,
  });

  @override
  int get hashCode =>
      itemCount.hashCode ^
      totalCost.hashCode ^
      totalRevenue.hashCode ^
      grossProfit.hashCode ^
      marginPercent.hashCode ^
      currency.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OrderTotals &&
          runtimeType == other.runtimeType &&
          itemCount == other.itemCount &&
          totalCost == other.totalCost &&
          totalRevenue == other.totalRevenue &&
          grossProfit == other.grossProfit &&
          marginPercent == other.marginPercent &&
          currency == other.currency;
}

class OrderWithItems {
  final Order order;
  final List<OrderItem> items;
  final OrderTotals totals;

  const OrderWithItems({
    required this.order,
    required this.items,
    required this.totals,
  });

  @override
  int get hashCode => order.hashCode ^ items.hashCode ^ totals.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OrderWithItems &&
          runtimeType == other.runtimeType &&
          order == other.order &&
          items == other.items &&
          totals == other.totals;
}

class Port {
  final int id;
  final String name;
  final String country;
  final String? city;
  final String timezone;
  final double? latitude;
  final double? longitude;
  final String? notes;
  final bool isActive;
  final String createdAt;
  final String updatedAt;

  const Port({
    required this.id,
    required this.name,
    required this.country,
    this.city,
    required this.timezone,
    this.latitude,
    this.longitude,
    this.notes,
    required this.isActive,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      country.hashCode ^
      city.hashCode ^
      timezone.hashCode ^
      latitude.hashCode ^
      longitude.hashCode ^
      notes.hashCode ^
      isActive.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Port &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          country == other.country &&
          city == other.city &&
          timezone == other.timezone &&
          latitude == other.latitude &&
          longitude == other.longitude &&
          notes == other.notes &&
          isActive == other.isActive &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

class Ship {
  final int id;
  final String name;
  final String imoNumber;
  final String flag;
  final String? shipType;
  final double? grossTonnage;
  final String? owner;
  final String createdAt;
  final String updatedAt;

  const Ship({
    required this.id,
    required this.name,
    required this.imoNumber,
    required this.flag,
    this.shipType,
    this.grossTonnage,
    this.owner,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      imoNumber.hashCode ^
      flag.hashCode ^
      shipType.hashCode ^
      grossTonnage.hashCode ^
      owner.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Ship &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          imoNumber == other.imoNumber &&
          flag == other.flag &&
          shipType == other.shipType &&
          grossTonnage == other.grossTonnage &&
          owner == other.owner &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

class ShipVisit {
  final int id;
  final int shipId;
  final String? shipName;
  final int portId;
  final String? portName;
  final String eta;
  final String etd;
  final String? ata;
  final String? atd;
  final VisitStatus status;
  final String? agentInfo;
  final String? notes;
  final String createdAt;
  final String updatedAt;

  const ShipVisit({
    required this.id,
    required this.shipId,
    this.shipName,
    required this.portId,
    this.portName,
    required this.eta,
    required this.etd,
    this.ata,
    this.atd,
    required this.status,
    this.agentInfo,
    this.notes,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      shipId.hashCode ^
      shipName.hashCode ^
      portId.hashCode ^
      portName.hashCode ^
      eta.hashCode ^
      etd.hashCode ^
      ata.hashCode ^
      atd.hashCode ^
      status.hashCode ^
      agentInfo.hashCode ^
      notes.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShipVisit &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          shipId == other.shipId &&
          shipName == other.shipName &&
          portId == other.portId &&
          portName == other.portName &&
          eta == other.eta &&
          etd == other.etd &&
          ata == other.ata &&
          atd == other.atd &&
          status == other.status &&
          agentInfo == other.agentInfo &&
          notes == other.notes &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

/// Current stock level for a product
class Stock {
  final int id;
  final int supplyItemId;
  final String? supplyItemName;
  final double quantity;
  final String unit;
  final String? warehouseLocation;
  final double minimumQuantity;
  final String lastUpdated;

  const Stock({
    required this.id,
    required this.supplyItemId,
    this.supplyItemName,
    required this.quantity,
    required this.unit,
    this.warehouseLocation,
    required this.minimumQuantity,
    required this.lastUpdated,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      supplyItemId.hashCode ^
      supplyItemName.hashCode ^
      quantity.hashCode ^
      unit.hashCode ^
      warehouseLocation.hashCode ^
      minimumQuantity.hashCode ^
      lastUpdated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Stock &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          supplyItemId == other.supplyItemId &&
          supplyItemName == other.supplyItemName &&
          quantity == other.quantity &&
          unit == other.unit &&
          warehouseLocation == other.warehouseLocation &&
          minimumQuantity == other.minimumQuantity &&
          lastUpdated == other.lastUpdated;
}

/// Stock movement record
class StockMovement {
  final int id;
  final int stockId;
  final String? supplyItemName;
  final StockMovementType movementType;
  final double quantity;
  final String unit;
  final String? referenceType;
  final int? referenceId;
  final String? referenceInfo;
  final String? notes;
  final String createdAt;

  const StockMovement({
    required this.id,
    required this.stockId,
    this.supplyItemName,
    required this.movementType,
    required this.quantity,
    required this.unit,
    this.referenceType,
    this.referenceId,
    this.referenceInfo,
    this.notes,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      stockId.hashCode ^
      supplyItemName.hashCode ^
      movementType.hashCode ^
      quantity.hashCode ^
      unit.hashCode ^
      referenceType.hashCode ^
      referenceId.hashCode ^
      referenceInfo.hashCode ^
      notes.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StockMovement &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          stockId == other.stockId &&
          supplyItemName == other.supplyItemName &&
          movementType == other.movementType &&
          quantity == other.quantity &&
          unit == other.unit &&
          referenceType == other.referenceType &&
          referenceId == other.referenceId &&
          referenceInfo == other.referenceInfo &&
          notes == other.notes &&
          createdAt == other.createdAt;
}

/// Stock movement type - what kind of inventory change
enum StockMovementType {
  /// Goods received from supplier
  in_,

  /// Goods sent to ship
  out,

  /// Inventory adjustment (count correction)
  adjustment,

  /// Return from ship
  return_,
  ;
}

/// Stock summary for dashboard
class StockSummary {
  final int totalItems;
  final int lowStockCount;
  final int outOfStockCount;
  final double totalValue;
  final String currency;

  const StockSummary({
    required this.totalItems,
    required this.lowStockCount,
    required this.outOfStockCount,
    required this.totalValue,
    required this.currency,
  });

  @override
  int get hashCode =>
      totalItems.hashCode ^
      lowStockCount.hashCode ^
      outOfStockCount.hashCode ^
      totalValue.hashCode ^
      currency.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StockSummary &&
          runtimeType == other.runtimeType &&
          totalItems == other.totalItems &&
          lowStockCount == other.lowStockCount &&
          outOfStockCount == other.outOfStockCount &&
          totalValue == other.totalValue &&
          currency == other.currency;
}

/// Stock with movement history
class StockWithMovements {
  final Stock stock;
  final List<StockMovement> movements;

  const StockWithMovements({
    required this.stock,
    required this.movements,
  });

  @override
  int get hashCode => stock.hashCode ^ movements.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StockWithMovements &&
          runtimeType == other.runtimeType &&
          stock == other.stock &&
          movements == other.movements;
}

class Supplier {
  final int id;
  final String name;
  final String? contactPerson;
  final String? email;
  final String? phone;
  final String? address;
  final String? country;
  final String category;
  final bool isActive;
  final String createdAt;
  final String updatedAt;

  const Supplier({
    required this.id,
    required this.name,
    this.contactPerson,
    this.email,
    this.phone,
    this.address,
    this.country,
    required this.category,
    required this.isActive,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      contactPerson.hashCode ^
      email.hashCode ^
      phone.hashCode ^
      address.hashCode ^
      country.hashCode ^
      category.hashCode ^
      isActive.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Supplier &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          contactPerson == other.contactPerson &&
          email == other.email &&
          phone == other.phone &&
          address == other.address &&
          country == other.country &&
          category == other.category &&
          isActive == other.isActive &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

class SupplyItem {
  final int id;
  final int supplierId;
  final String? supplierName;
  final String? impaCode;
  final String name;
  final String? description;
  final String category;
  final String unit;
  final double unitPrice;
  final String currency;
  final int? minimumOrderQuantity;
  final bool isAvailable;
  final String createdAt;
  final String updatedAt;

  const SupplyItem({
    required this.id,
    required this.supplierId,
    this.supplierName,
    this.impaCode,
    required this.name,
    this.description,
    required this.category,
    required this.unit,
    required this.unitPrice,
    required this.currency,
    this.minimumOrderQuantity,
    required this.isAvailable,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      supplierId.hashCode ^
      supplierName.hashCode ^
      impaCode.hashCode ^
      name.hashCode ^
      description.hashCode ^
      category.hashCode ^
      unit.hashCode ^
      unitPrice.hashCode ^
      currency.hashCode ^
      minimumOrderQuantity.hashCode ^
      isAvailable.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SupplyItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          supplierId == other.supplierId &&
          supplierName == other.supplierName &&
          impaCode == other.impaCode &&
          name == other.name &&
          description == other.description &&
          category == other.category &&
          unit == other.unit &&
          unitPrice == other.unitPrice &&
          currency == other.currency &&
          minimumOrderQuantity == other.minimumOrderQuantity &&
          isAvailable == other.isAvailable &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

class UpdateOrderItemRequest {
  final String? productName;
  final String? impaCode;
  final String? description;
  final double? quantity;
  final String? unit;
  final double? buyingPrice;
  final double? sellingPrice;
  final DeliveryType? deliveryType;
  final String? warehouseDeliveryDate;
  final String? shipDeliveryDate;
  final String? notes;

  const UpdateOrderItemRequest({
    this.productName,
    this.impaCode,
    this.description,
    this.quantity,
    this.unit,
    this.buyingPrice,
    this.sellingPrice,
    this.deliveryType,
    this.warehouseDeliveryDate,
    this.shipDeliveryDate,
    this.notes,
  });

  @override
  int get hashCode =>
      productName.hashCode ^
      impaCode.hashCode ^
      description.hashCode ^
      quantity.hashCode ^
      unit.hashCode ^
      buyingPrice.hashCode ^
      sellingPrice.hashCode ^
      deliveryType.hashCode ^
      warehouseDeliveryDate.hashCode ^
      shipDeliveryDate.hashCode ^
      notes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateOrderItemRequest &&
          runtimeType == other.runtimeType &&
          productName == other.productName &&
          impaCode == other.impaCode &&
          description == other.description &&
          quantity == other.quantity &&
          unit == other.unit &&
          buyingPrice == other.buyingPrice &&
          sellingPrice == other.sellingPrice &&
          deliveryType == other.deliveryType &&
          warehouseDeliveryDate == other.warehouseDeliveryDate &&
          shipDeliveryDate == other.shipDeliveryDate &&
          notes == other.notes;
}

class UpdatePortRequest {
  final String? name;
  final String? country;
  final String? city;
  final String? timezone;
  final double? latitude;
  final double? longitude;
  final String? notes;
  final bool? isActive;

  const UpdatePortRequest({
    this.name,
    this.country,
    this.city,
    this.timezone,
    this.latitude,
    this.longitude,
    this.notes,
    this.isActive,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      country.hashCode ^
      city.hashCode ^
      timezone.hashCode ^
      latitude.hashCode ^
      longitude.hashCode ^
      notes.hashCode ^
      isActive.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdatePortRequest &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          country == other.country &&
          city == other.city &&
          timezone == other.timezone &&
          latitude == other.latitude &&
          longitude == other.longitude &&
          notes == other.notes &&
          isActive == other.isActive;
}

class UpdateShipRequest {
  final String? name;
  final String? imoNumber;
  final String? flag;
  final String? shipType;
  final double? grossTonnage;
  final String? owner;

  const UpdateShipRequest({
    this.name,
    this.imoNumber,
    this.flag,
    this.shipType,
    this.grossTonnage,
    this.owner,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      imoNumber.hashCode ^
      flag.hashCode ^
      shipType.hashCode ^
      grossTonnage.hashCode ^
      owner.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateShipRequest &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          imoNumber == other.imoNumber &&
          flag == other.flag &&
          shipType == other.shipType &&
          grossTonnage == other.grossTonnage &&
          owner == other.owner;
}

class UpdateShipVisitRequest {
  final int? portId;
  final String? eta;
  final String? etd;
  final String? ata;
  final String? atd;
  final VisitStatus? status;
  final String? agentInfo;
  final String? notes;

  const UpdateShipVisitRequest({
    this.portId,
    this.eta,
    this.etd,
    this.ata,
    this.atd,
    this.status,
    this.agentInfo,
    this.notes,
  });

  @override
  int get hashCode =>
      portId.hashCode ^
      eta.hashCode ^
      etd.hashCode ^
      ata.hashCode ^
      atd.hashCode ^
      status.hashCode ^
      agentInfo.hashCode ^
      notes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateShipVisitRequest &&
          runtimeType == other.runtimeType &&
          portId == other.portId &&
          eta == other.eta &&
          etd == other.etd &&
          ata == other.ata &&
          atd == other.atd &&
          status == other.status &&
          agentInfo == other.agentInfo &&
          notes == other.notes;
}

class UpdateStockRequest {
  final double? quantity;
  final String? warehouseLocation;
  final double? minimumQuantity;

  const UpdateStockRequest({
    this.quantity,
    this.warehouseLocation,
    this.minimumQuantity,
  });

  @override
  int get hashCode =>
      quantity.hashCode ^ warehouseLocation.hashCode ^ minimumQuantity.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateStockRequest &&
          runtimeType == other.runtimeType &&
          quantity == other.quantity &&
          warehouseLocation == other.warehouseLocation &&
          minimumQuantity == other.minimumQuantity;
}

class UpdateSupplierRequest {
  final String? name;
  final String? contactPerson;
  final String? email;
  final String? phone;
  final String? address;
  final String? country;
  final String? category;

  const UpdateSupplierRequest({
    this.name,
    this.contactPerson,
    this.email,
    this.phone,
    this.address,
    this.country,
    this.category,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      contactPerson.hashCode ^
      email.hashCode ^
      phone.hashCode ^
      address.hashCode ^
      country.hashCode ^
      category.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateSupplierRequest &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          contactPerson == other.contactPerson &&
          email == other.email &&
          phone == other.phone &&
          address == other.address &&
          country == other.country &&
          category == other.category;
}

class UpdateSupplyItemRequest {
  final int? supplierId;
  final String? impaCode;
  final String? name;
  final String? description;
  final String? category;
  final String? unit;
  final double? unitPrice;
  final String? currency;
  final int? minimumOrderQuantity;
  final bool? isAvailable;

  const UpdateSupplyItemRequest({
    this.supplierId,
    this.impaCode,
    this.name,
    this.description,
    this.category,
    this.unit,
    this.unitPrice,
    this.currency,
    this.minimumOrderQuantity,
    this.isAvailable,
  });

  @override
  int get hashCode =>
      supplierId.hashCode ^
      impaCode.hashCode ^
      name.hashCode ^
      description.hashCode ^
      category.hashCode ^
      unit.hashCode ^
      unitPrice.hashCode ^
      currency.hashCode ^
      minimumOrderQuantity.hashCode ^
      isAvailable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateSupplyItemRequest &&
          runtimeType == other.runtimeType &&
          supplierId == other.supplierId &&
          impaCode == other.impaCode &&
          name == other.name &&
          description == other.description &&
          category == other.category &&
          unit == other.unit &&
          unitPrice == other.unitPrice &&
          currency == other.currency &&
          minimumOrderQuantity == other.minimumOrderQuantity &&
          isAvailable == other.isAvailable;
}

/// Ship visit status
enum VisitStatus {
  planned,
  arrived,
  departed,
  cancelled,
  ;
}
